In [64]:
#Load all libraries
import pandas as pd
import numpy as np
import datetime as datetime
import datetime as timedelta
import pickle

In [65]:
from sklearn import decomposition
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn import svm

In [66]:
#Read all match results
results=pd.read_csv("D:\\Data Science\\World Cup\\results.csv")

In [99]:
results.head()

,Date,Team_A,Team_B,Team_A_score,Team_B_score,tournament,Winner_Team
834,1925-02-14,Scotland,Wales,3,1,British Championship,Scotland
835,1925-02-28,Northern-Ireland,Scotland,0,3,British Championship,Scotland
836,1925-02-28,Wales,England,1,2,British Championship,England
837,1925-03-15,Belgium,Netherlands,0,1,Friendly,Netherlands
838,1925-03-22,Austria,Switzerland,2,0,Friendly,Austria

In [68]:
#Create Year column 
results['Year']=results.date.map(lambda x: x.split("-")[0])
results.Year = pd.to_numeric(results.Year)

In [69]:
results.Year.unique()

array([1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882,
       1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893,
       1894, 1895, 1896, 1897, 1898, 1899,    3,   24,   17,   26,    7,
         23,    2,    9,   18,   30,   22,    1,   15,   20,   12,   21,
         28,    4,    5,   13,   11,   29,   25,    6,   27,    8,   14,
         19,   16,   10,   31], dtype=int64)

In [70]:
## Extract matches from 1900 only 
results = results[ results.Year<1872]

In [71]:
results.shape

(38776, 9)

In [72]:
#Create Year column 
results['Year']=results.date.map(lambda x: x.split("-")[2])
results.Year = pd.to_numeric(results.Year)

In [73]:
## Extract matches from 1925 only 
results = results[ results.Year>=1925]

In [74]:
results.shape

(38068, 9)

In [75]:
results.to_csv("D:\\Data Science\\World Cup\\result_cleaned.csv")

In [76]:
#Find list of countries played match from  1872-2018
results_team_A=results.Team_A.unique()
results_team_B = results.Team_B.unique()
all_team_result = np.append(results_team_A,results_team_B)
all_team_result=pd.Series(all_team_result)

In [77]:
all_team_result=pd.Series(all_team_result.unique())

In [78]:
## Read all world cup matches starting from 1930
world_cup_result=pd.read_excel("D:\\Data Science\\World Cup\\World-Cup-Master-Data.xlsx")

In [79]:
#Exclude 2018 world cup
historical_data=world_cup_result[(world_cup_result.Year < 2018) | ((world_cup_result.Year==2018) & (world_cup_result.Round=="Group")) ]

In [80]:
historical_data.shape

(884, 15)

In [81]:
#Find list of countries played world cup from  1930
def filter_world_cup_playing_country(historical_data,results):
    all_team_A = historical_data.Team_A.unique()
    all_team_B = historical_data.Team_B.unique()
    all_team = np.append(all_team_A,all_team_B)
    all_team=pd.Series(all_team)

    #Conside matches played by all countries who have played worldcup
    results=results[ results.Team_A.isin(all_team) | results.Team_B.isin(all_team)]

    results.head()

    ##Convert date to datetime format
    results.date=pd.to_datetime(results.date)

    ##Select only relevent columns
    results=results[["date","Team_A","Team_B","Team_A_score","Team_B_score","tournament"]]

    #Rename date columns to Date
    results.rename(columns={'date': 'Date'},inplace=True)
    
    return (results)

In [82]:
results=filter_world_cup_playing_country(historical_data,results)

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\generic.py:4401: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [83]:
results.shape

(27901, 6)

In [84]:
##Function to create Winner attributes. This variable will be used as dependent variable.
def winner(x):
    if x.Team_A_score>x.Team_B_score:
        val = x.Team_A
    elif x.Team_A_score<x.Team_B_score:
        val = x.Team_B
    elif x.Team_A_score==x.Team_B_score:
        val = "Draw"
    return (val)

In [85]:
##Apply winner function
results['Winner_Team']=results.apply(winner,axis=1)

In [86]:
### Include worldcup result from worldcup data 
results_wthout_worldcup = results[ ~(results.tournament=='FIFA World Cup')]

#Select relevent column to merge with all match result
world_cup_data=world_cup_result[["Date","Team_A","Team_B","Team_A_score","Team_B_score","Winner_Team"]]

results_wthout_worldcup.drop('tournament',axis=1,inplace=True)

#Merge both data
result_all_match=results_wthout_worldcup.append(world_cup_data)

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\frame.py:3694: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [87]:
result_all_match.Date=pd.to_datetime(result_all_match.Date)

In [88]:
#historical_data.Date=pd.to_datetime(historical_data.Date)

In [89]:
historical_data.tail()

,Month,Place,Team_A,Team_B,Team_A_score,Team_B_score,Venue,City,Year,day,Date,Round,Winner_Team,Winner,rest
879,6,Russia,Mexico,Sweden,NaN,NaN,Central Stadium,Yekaterinburg,2018,27,27-6-2018,Group,NaN,Team_B,(44) Wed Jun/27 19:00 Mexico - Sweden @ Centra...
880,6,Russia,Japan,Poland,NaN,NaN,Volgograd Arena,Volgograd,2018,28,28-6-2018,Group,NaN,Team_B,(47) Thu Jun/28 17:00 Japan - Poland @ Volgogr...
881,6,Russia,Senegal,Colombia,NaN,NaN,Cosmos Arena,Samara,2018,28,28-6-2018,Group,NaN,Team_B,(48) Thu Jun/28 18:00 Senegal - Colombia @ Cos...
882,6,Russia,Panama,Tunisia,NaN,NaN,Mordovia Arena,Saransk,2018,28,28-6-2018,Group,NaN,NaN,NaN
883,6,Russia,England,Belgium,NaN,NaN,Kaliningrad Stadium,Kaliningrad,2018,28,28-6-2018,Group,NaN,NaN,NaN

In [90]:
### Calculate head to head performance for each country in world cup before each match
def wc_h2h_calculation(x):
    winner_count=[]

    for dt in x.Date.unique():
        prev_matches=historical_data[ historical_data.Date<dt]
        curr_matches=historical_data[ historical_data.Date==dt]
        print(dt)
        for index in curr_matches.index:
            ht = curr_matches.Team_A[index]
            at = curr_matches.Team_B[index]
            win_ct=prev_matches[(prev_matches['Team_A'].isin([ht,at])) & (prev_matches['Team_B'].isin([ht,at]))].Winner_Team.value_counts()

            if (win_ct.shape[0]>1) & (win_ct.index.isin([ht,at]).sum()>1):

                ht_index=np.where(win_ct.index.isin([ht])==True)[0][0]

                at_index=np.where(win_ct.index.isin([at])==True)[0][0]

                winner_count.append({'Date': dt,'Team_A':ht,'Team_B':at,'Team_A_head2head_win_wc':win_ct[ht_index],'Team_B_head2head_win_wc':win_ct[at_index],'No_of_match_head_2_head_wc':sum(win_ct)})

                #winner_count=winner_count.append(winner_temp)

            elif (win_ct.shape[0]==1) & (win_ct.index.isin([ht,at]).sum()==1) & (win_ct.index.isin([ht]).sum()>0):

                #print ([ht,at])

                ht_index=np.where(win_ct.index.isin([ht])==True)[0][0]

                winner_count.append({'Date': dt,'Team_A':ht,'Team_B':at,'Team_A_head2head_win_wc':win_ct[ht_index],'Team_B_head2head_win_wc':0,'No_of_match_head_2_head_wc':sum(win_ct)})

            elif (win_ct.shape[0]==1) & (win_ct.index.isin([ht,at]).sum()==1) & (win_ct.index.isin([at]).sum()>0):

                #print ([ht,at])

                at_index=np.where(win_ct.index.isin([at])==True)[0][0]

                winner_count.append({'Date': dt,'Team_A':ht,'Team_B':at,'Team_A_head2head_win_wc':0,'Team_B_head2head_win_wc':win_ct[at_index],'No_of_match_head_2_head_wc':sum(win_ct)})
            
            else:

                #print ([ht,at])

                winner_count.append({'Date': dt,'Team_A':ht,'Team_B':at,'Team_A_head2head_win_wc':0,'Team_B_head2head_win_wc':0,'No_of_match_head_2_head_wc':0})

    winner_count_Worldcup=pd.DataFrame(winner_count)

    winner_count_Worldcup['Draw_wc']=winner_count_Worldcup.No_of_match_head_2_head_wc-(winner_count_Worldcup.Team_A_head2head_win_wc+winner_count_Worldcup.Team_B_head2head_win_wc)
    
    return (winner_count_Worldcup)

In [91]:
### Calculates head to head performance for each country before each match
def all_match_h2h_calculation(x):
    winner_count=[]

    for dt in x.Date.unique():
        prev_matches=result_all_match[ result_all_match.Date<dt]
        curr_matches=historical_data[ historical_data.Date==dt]
        print(dt)
        for index in curr_matches.index:
            ht = curr_matches.Team_A[index]
            at = curr_matches.Team_B[index]        
            win_ct=prev_matches[(prev_matches['Team_A'].isin([ht,at])) & (prev_matches['Team_B'].isin([ht,at]))].Winner_Team.value_counts()

            if (win_ct.shape[0]>1) & (win_ct.index.isin([ht,at]).sum()>1):

                ht_index=np.where(win_ct.index.isin([ht])==True)[0][0]

                at_index=np.where(win_ct.index.isin([at])==True)[0][0]

                winner_count.append({'Date': dt,'Team_A':ht,'Team_B':at,'Team_A_head2head_win_all_match':win_ct[ht_index],'Team_B_head2head_win_all_match':win_ct[at_index],'No_of_match_head_2_head_all':sum(win_ct)})

                #winner_count=winner_count.append(winner_temp)

            elif (win_ct.shape[0]==1) & (win_ct.index.isin([ht,at]).sum()==1) & (win_ct.index.isin([ht]).sum()>0):

                #print ([ht,at])

                ht_index=np.where(win_ct.index.isin([ht])==True)[0][0]

                winner_count.append({'Date': dt,'Team_A':ht,'Team_B':at,'Team_A_head2head_win_all_match':win_ct[ht_index],'Team_B_head2head_win_all_match':0,'No_of_match_head_2_head_all':sum(win_ct)})

            elif (win_ct.shape[0]==1) & (win_ct.index.isin([ht,at]).sum()==1) & (win_ct.index.isin([at]).sum()>0):

                #print ([ht,at])

                at_index=np.where(win_ct.index.isin([at])==True)[0][0]

                winner_count.append({'Date': dt,'Team_A':ht,'Team_B':at,'Team_A_head2head_win_all_match':0,'Team_B_head2head_win_all_match':win_ct[at_index],'No_of_match_head_2_head_all':sum(win_ct)})
            else:
                winner_count.append({'Date': dt,'Team_A':ht,'Team_B':at,'Team_A_head2head_win_all_match':0,'Team_B_head2head_win_all_match':0,'No_of_match_head_2_head_all':0})
        
    winner_count_all_match=pd.DataFrame(winner_count)

    winner_count_all_match['Draw_all_match']=winner_count_all_match.No_of_match_head_2_head_all-(winner_count_all_match.Team_A_head2head_win_all_match+winner_count_all_match.Team_B_head2head_win_all_match)
    return (winner_count_all_match)

In [92]:
### Calculates head to head performance for each country before each match in last 10 years
def h2h_all_10yrs(x):
    
    #Function to calculate date before few years
    def subtract_years(dt, years):
        try:
            dt = dt.replace(year=dt.year-years)
        except ValueError:
            dt = dt.replace(year=dt.year-years, day=dt.day-1)
        return dt
    #historical_data.Date=pd.to_datetime(historical_data.Date)
    winner_count=[]
    x.Date=x.Date.astype('M8[ms]').astype('O')
    for dt in x.Date.unique():
        prev_matches=result_all_match[ (result_all_match.Date<dt) & (result_all_match.Date>subtract_years(dt,10))]
        curr_matches=historical_data[ historical_data.Date==dt]
        print(dt)
        for index in curr_matches.index:
            ht = curr_matches.Team_A[index]
            at = curr_matches.Team_B[index]        
            win_ct=prev_matches[(prev_matches['Team_A'].isin([ht,at])) & (prev_matches['Team_B'].isin([ht,at]))].Winner_Team.value_counts()

            if (win_ct.shape[0]>1) & (win_ct.index.isin([ht,at]).sum()>1):

                ht_index=np.where(win_ct.index.isin([ht])==True)[0][0]

                at_index=np.where(win_ct.index.isin([at])==True)[0][0]

                winner_count.append({'Date': dt,'Team_A':ht,'Team_B':at,'Team_A_win_all_match_10yr':win_ct[ht_index],'Team_B_win_all_match_10yr':win_ct[at_index],'No_of_match_head_2_head_all_10yr':sum(win_ct)})

                #winner_count=winner_count.append(winner_temp)

            elif (win_ct.shape[0]==1) & (win_ct.index.isin([ht,at]).sum()==1) & (win_ct.index.isin([ht]).sum()>0):

                #print ([ht,at])

                ht_index=np.where(win_ct.index.isin([ht])==True)[0][0]

                winner_count.append({'Date': dt,'Team_A':ht,'Team_B':at,'Team_A_win_all_match_10yr':win_ct[ht_index],'Team_B_win_all_match_10yr':0,'No_of_match_head_2_head_all_10yr':sum(win_ct)})

            elif (win_ct.shape[0]==1) & (win_ct.index.isin([ht,at]).sum()==1) & (win_ct.index.isin([at]).sum()>0):

                #print ([ht,at])

                at_index=np.where(win_ct.index.isin([at])==True)[0][0]

                winner_count.append({'Date': dt,'Team_A':ht,'Team_B':at,'Team_A_win_all_match_10yr':0,'Team_B_win_all_match_10yr':win_ct[at_index],'No_of_match_head_2_head_all_10yr':sum(win_ct)})
            else:
                winner_count.append({'Date': dt,'Team_A':ht,'Team_B':at,'Team_A_win_all_match_10yr':0,'Team_B_win_all_match_10yr':0,'No_of_match_head_2_head_all_10yr':0})
        
    winner_count_all_match_last_10_yr=pd.DataFrame(winner_count)

    winner_count_all_match_last_10_yr['Draw_all_match_10yr']=winner_count_all_match_last_10_yr.No_of_match_head_2_head_all_10yr-(winner_count_all_match_last_10_yr.Team_A_win_all_match_10yr+winner_count_all_match_last_10_yr.Team_B_win_all_match_10yr)
    
    return (winner_count_all_match_last_10_yr)

In [93]:
### Calculates each team performance in all matches
def team_performance_all_match(x):
    winner_count=[]

    for dt in x.Date.unique():
        prev_matches=result_all_match[ result_all_match.Date<dt]
        curr_matches=historical_data[ historical_data.Date==dt]
        print(dt)
        for team_list in pd.Series(np.append(curr_matches.Team_A,curr_matches.Team_B)):
            
            no_of_matches = prev_matches[(prev_matches['Team_A'].isin([team_list])) | (prev_matches['Team_B'].isin([team_list]))]
            win_ct=no_of_matches.Winner_Team.value_counts()
            
            if (win_ct.shape[0]>1) & (win_ct.index.isin([team_list]).sum()==1):
                if win_ct.index.isin(["Draw"]).sum()==1:
                    draw=win_ct["Draw"]
                else:
                    draw=0
                ht_index=np.where(win_ct.index.isin([team_list])==True)[0][0]
                winner_count.append({'Date': dt,'Team':team_list,'all_match_win':win_ct[ht_index],'all_match_Draw':draw,'Total_match':no_of_matches.shape[0]})

                #winner_count=winner_count.append(winner_temp)

            elif (win_ct.shape[0]==1) & (win_ct.index.isin([team_list]).sum()==1):

                winner_count.append({'Date': dt,'Team':team_list,'all_match_win':win_ct[0],'all_match_Draw':0,'Total_match':no_of_matches.shape[0]})

            elif (win_ct.shape[0]==1) & (win_ct.index.isin([team_list]).sum()==0):
                if win_ct.index.isin(["Draw"]).sum()==1:
                    draw=win_ct["Draw"]
                else:
                    draw=0
                winner_count.append({'Date': dt,'Team':team_list,'all_match_win':0,'all_match_Draw':draw,'Total_match':no_of_matches.shape[0]})
        
    winner_count_team_performance_all_match=pd.DataFrame(winner_count)
    historical_data.Date = historical_data.Date.map(lambda x: np.datetime64(x))
    print(winner_count_team_performance_all_match.dtypes)
    #Team_A
    winner_count_team_performance_all_match.rename(columns=({'all_match_win':'Team_A_all_match_win','all_match_Draw':'Team_A_all_match_Draw'}),inplace=True)
    right_df = winner_count_team_performance_all_match[['Date','Team','Team_A_all_match_win','Team_A_all_match_Draw']]
    World_cup_model_data = pd.merge(historical_data[['Date','Team_A','Team_B']],right_df,left_on=['Date','Team_A'],right_on=['Date','Team'],how='left')
    World_cup_model_data.drop(axis=1,labels='Team',inplace=True)
    #Team_B
    winner_count_team_performance_all_match.rename(columns=({'Team_A_all_match_win':'Team_B_all_match_win','Team_A_all_match_Draw':'Team_B_all_match_Draw'}),inplace=True)
    right_df = winner_count_team_performance_all_match[['Date','Team','Team_B_all_match_win','Team_B_all_match_Draw']]
    World_cup_model_data = pd.merge(World_cup_model_data,right_df,left_on=['Date','Team_B'],right_on=['Date','Team'],how='left')
    World_cup_model_data.drop(axis=1,labels='Team',inplace=True)
    return (World_cup_model_data)

In [94]:
### Calculates each team performance in world cup
def team_performance_wc_match(x):
    winner_count=[]

    for dt in x.Date.unique():
        prev_matches=historical_data[ historical_data.Date<dt]
        curr_matches=historical_data[ historical_data.Date==dt]
        print(dt)
        for team_list in pd.Series(np.append(curr_matches.Team_A,curr_matches.Team_B)):
            
            no_of_matches = prev_matches[(prev_matches['Team_A'].isin([team_list])) | (prev_matches['Team_B'].isin([team_list]))]
            win_ct=no_of_matches.Winner_Team.value_counts()
            
            if (win_ct.shape[0]>1) & (win_ct.index.isin([team_list]).sum()==1):
                if win_ct.index.isin(["Draw"]).sum()==1:
                    draw=win_ct["Draw"]
                else:
                    draw=0
                ht_index=np.where(win_ct.index.isin([team_list])==True)[0][0]
                winner_count.append({'Date': dt,'Team':team_list,'wc_win':win_ct[ht_index],'wc_Draw':draw,'Total_match':no_of_matches.shape[0]})

                #winner_count=winner_count.append(winner_temp)

            elif (win_ct.shape[0]==1) & (win_ct.index.isin([team_list]).sum()==1):

                winner_count.append({'Date': dt,'Team':team_list,'wc_win':win_ct[0],'wc_Draw':0,'Total_match':no_of_matches.shape[0]})

            elif (win_ct.shape[0]==1) & (win_ct.index.isin([team_list]).sum()==0):
                if win_ct.index.isin(["Draw"]).sum()==1:
                    draw=win_ct["Draw"]
                else:
                    draw=0
                winner_count.append({'Date': dt,'Team':team_list,'wc_win':0,'wc_Draw':draw,'Total_match':no_of_matches.shape[0]})
        
    winner_count_team_performance_wc=pd.DataFrame(winner_count)
    historical_data.Date = historical_data.Date.map(lambda x: np.datetime64(x))
    #Team_A
    winner_count_team_performance_wc.rename(columns=({'wc_win':'Team_A_wc_win','wc_Draw':'Team_A_wc_Draw'}),inplace=True)
    right_df = winner_count_team_performance_wc[['Date','Team','Team_A_wc_win','Team_A_wc_Draw']]
    World_cup_model_data = pd.merge(historical_data[['Date','Team_A','Team_B']],right_df,left_on=['Date','Team_A'],right_on=['Date','Team'],how='left')
    World_cup_model_data.drop(axis=1,labels='Team',inplace=True)
    #Team_B
    winner_count_team_performance_wc.rename(columns=({'Team_A_wc_win':'Team_B_wc_win','Team_A_wc_Draw':'Team_B_wc_Draw'}),inplace=True)
    right_df = winner_count_team_performance_wc[['Date','Team','Team_B_wc_win','Team_B_wc_Draw']]
    World_cup_model_data = pd.merge(World_cup_model_data,right_df,left_on=['Date','Team_B'],right_on=['Date','Team'],how='left')
    World_cup_model_data.drop(axis=1,labels='Team',inplace=True)
    
    return (World_cup_model_data)

In [95]:
### Calculates each team performance in last 10 match
def team_performance_all_match_10yr(x):
    winner_count=[]

    for dt in x.Date.unique():
        prev_matches=result_all_match[ result_all_match.Date<dt]
        curr_matches=historical_data[ historical_data.Date==dt]
        print(dt)
        for team_list in pd.Series(np.append(curr_matches.Team_A,curr_matches.Team_B)):
            
            no_of_matches = prev_matches[(prev_matches['Team_A'].isin([team_list])) | (prev_matches['Team_B'].isin([team_list]))]
            no_of_matches = no_of_matches.sort_values(by='Date',ascending=False).head(10)
            win_ct=no_of_matches.Winner_Team.value_counts()
            
            if (win_ct.shape[0]>1) & (win_ct.index.isin([team_list]).sum()==1):
                if win_ct.index.isin(["Draw"]).sum()==1:
                    draw=win_ct["Draw"]
                else:
                    draw=0
                ht_index=np.where(win_ct.index.isin([team_list])==True)[0][0]
                winner_count.append({'Date': dt,'Team':team_list,'last_10_match_win':win_ct[ht_index],'last_10_match_Draw':draw,'Total_match':no_of_matches.shape[0]})

                #winner_count=winner_count.append(winner_temp)

            elif (win_ct.shape[0]==1) & (win_ct.index.isin([team_list]).sum()==1):

                winner_count.append({'Date': dt,'Team':team_list,'last_10_match_win':win_ct[0],'last_10_match_Draw':0,'Total_match':no_of_matches.shape[0]})

            elif (win_ct.shape[0]==1) & (win_ct.index.isin([team_list]).sum()==0):
                if win_ct.index.isin(["Draw"]).sum()==1:
                    draw=win_ct["Draw"]
                else:
                    draw=0
                winner_count.append({'Date': dt,'Team':team_list,'last_10_match_win':0,'last_10_match_Draw':draw,'Total_match':no_of_matches.shape[0]})
        
    winner_count_team_performance_last_10_match=pd.DataFrame(winner_count)
    historical_data.Date = historical_data.Date.map(lambda x: np.datetime64(x))
    #Team_A
    winner_count_team_performance_last_10_match.rename(columns=({'last_10_match_win':'Team_A_last_10_match_win','last_10_match_Draw':'Team_A_last_10_match_Draw'}),inplace=True)
    right_df = winner_count_team_performance_last_10_match[['Date','Team','Team_A_last_10_match_win','Team_A_last_10_match_Draw']]
    World_cup_model_data = pd.merge(historical_data[['Date','Team_A','Team_B']],right_df,left_on=['Date','Team_A'],right_on=['Date','Team'],how='left')
    World_cup_model_data.drop(axis=1,labels='Team',inplace=True)
    #Team_B
    winner_count_team_performance_last_10_match.rename(columns=({'Team_A_last_10_match_win':'Team_B_last_10_match_win','Team_A_last_10_match_Draw':'Team_B_last_10_match_Draw'}),inplace=True)
    right_df = winner_count_team_performance_last_10_match[['Date','Team','Team_B_last_10_match_win','Team_B_last_10_match_Draw']]
    World_cup_model_data = pd.merge(World_cup_model_data,right_df,left_on=['Date','Team_B'],right_on=['Date','Team'],how='left')
    World_cup_model_data.drop(axis=1,labels='Team',inplace=True)
    
    return (World_cup_model_data)

In [252]:
#Extract Rank information
def rank_calculation(x):
    
    #Extract rank information from 1993-09 - present
    Rank=pd.read_excel("D:\\Data Science\\World Cup\\Rank File.xlsx")

    # unpivot the data
    Rank=pd.melt(Rank, id_vars=['Date'], var_name='Team', value_name='Rank')

    #Create Year and Month column
    Rank['Year'] = pd.to_numeric(Rank.Date.map(lambda x: x.year))
    Rank['Month']=pd.to_numeric(Rank.Date.map(lambda x: x.month))
    
    if min(x.Date)<datetime.datetime(1993,7,1):
        result_all_match_rank = results.copy()

        result_all_match_rank['Month']=result_all_match_rank.Date.map(lambda x: x.month)
        result_all_match_rank['Year']=result_all_match_rank.Date.map(lambda x: x.year)

        result_all_match_rank['Year']=result_all_match_rank['Year']+result_all_match_rank['Month']/12

        #Calculate Rank for teams before ranking system starts on 1993-08
        winner_count=[]
        for year in np.arange(1930,1993.6,1/12):
            print (year)
            sel_df = result_all_match_rank[ result_all_match_rank.Year<year]
    
            for team_list in pd.Series(np.append(sel_df.Team_A.unique(),sel_df.Team_B.unique())).unique():
                no_of_matches = sel_df[(sel_df['Team_A'].isin([team_list])) | (sel_df['Team_B'].isin([team_list]))]
                win_ct=no_of_matches.Winner_Team.value_counts()
                if sum(win_ct.index.isin([team_list]))==1 :
                    win_pt = win_ct[np.where(win_ct.index.isin([team_list])==True)[0][0]]
                else:
                    win_pt = 0
                if sum(win_ct.index.isin(["Draw"]))==1:
                    Draw_pt = win_ct[np.where(win_ct.index.isin(["Draw"])==True)[0][0]]
                else:
                    Draw_pt = 0
        
                point = win_pt*3+Draw_pt*1
                winner_count.append({'Year': year,'Team':team_list,'Point':point})
                
        Team_Rank_before_1993_7=pd.DataFrame(winner_count)
        #if else need to use

        Team_Rank_before_1993_7=Team_Rank_before_1993_7.sort_values(by=['Year','Point'],ascending=[1,0])

        Team_Rank_before_1993_7['Rank']=Team_Rank_before_1993_7.groupby(['Year'])['Point'].rank(ascending=False,method='dense')

        def month_conversion(x):
            month=(x%int(x))*12
            Year = int(x)
        if month==0:
            month = 12
            Year = Year-1
            return (month,Year)

        nec = Team_Rank_before_1993_7['Year'].apply(month_conversion)

        Team_Rank_before_1993_7['Month']=nec.map(lambda x: x[0])
        Team_Rank_before_1993_7['Year']=nec.map(lambda x: x[1])

        Team_Rank_before_1993_7.to_csv("D:\\Data Science\\World Cup\\Team_Rank_before_1993_7.csv")

    Team_Rank_before_1993_7=pd.read_csv("D:\\Data Science\\World Cup\\Team_Rank_before_1993_7.csv")
    Rank=pd.concat([Team_Rank_before_1993_7[['Year','Month','Team','Rank']],Rank[['Year','Month','Team','Rank']]],ignore_index=True)
     

    Rank.Year = np.int64(Rank.Year)
    Rank.Month = np.int64(Rank.Month)
    Rank.Rank = np.int64(Rank.Rank)

    def add_one_month(x):
        if x.Month < 12:
            month1=x.Month+1
            year1=x.Year
        elif x.Month==12:
            month1=1
            year1=(x.Year+1)
        return [month1,year1]

    next_value=Rank[['Month','Year']].apply(add_one_month,axis=1)

    Rank['Next_Month']=next_value.map(lambda x: x[0])
    Rank['Next_Year']=next_value.map(lambda x: x[1])

    def month_processing(x):
        if (x.Month > 6) & (x.Year==2018):
            month1=6
        else :
            month1=x.Month
        return (month1)

    temp_rank_df=historical_data.copy()

    temp_rank_df['Changed_Month']=temp_rank_df[['Month','Year']].apply(month_processing,axis=1)
    
    #merge with world cup result data 
    #Includes Team_A rank
    rank_df=pd.merge(temp_rank_df[['Month','Changed_Month','Year','Team_A','Team_B']],Rank[['Next_Month','Next_Year','Team','Rank']],left_on=['Changed_Month','Year','Team_A'],right_on=['Next_Month','Next_Year','Team'],how='left')
    rank_df.drop(axis=1,labels=['Next_Month','Next_Year','Team'],inplace=True)
    rank_df.rename(columns={'Rank':'Rank_Team_A'},inplace=True)

    #merge with world cup result data 
    #Includes Team_B rank
    rank_df=pd.merge(rank_df,Rank[['Next_Month','Next_Year','Team','Rank']],left_on=['Changed_Month','Year','Team_B'],right_on=['Next_Month','Next_Year','Team'],how='left')
    rank_df.drop(axis=1,labels=['Next_Month','Next_Year','Team'],inplace=True)
    rank_df.rename(columns={'Rank':'Rank_Team_B'},inplace=True)
    
    return (rank_df)

In [44]:
#Calculate each team's participation
def appearance_calculation(x):
    Appearance_df=[]
    for year in x.Year.unique():
        filtered_df=historical_data[(historical_data.Year<year)]
        curr_filter_df = historical_data[(historical_data.Year==year)]
        for team in pd.Series(np.append(curr_filter_df.Team_A,curr_filter_df.Team_B)).unique():
            filtered_df_team=filtered_df[(filtered_df.Team_A==team) | (filtered_df.Team_B==team)]
            Appearance_df.append({'Year':year,'Team':team,'Appearance':filtered_df_team.shape[0]})
    Appearance_df=pd.DataFrame(Appearance_df)

    #merge with world cup result data 
    #Includes Team_A Appearance
    World_cup_Appearance_df=pd.merge(historical_data[['Year','Team_A','Team_B']],Appearance_df,left_on=['Team_A','Year'],right_on=['Team','Year'],how='left')
    World_cup_Appearance_df.drop(axis=1,labels=['Team'],inplace=True)
    World_cup_Appearance_df.rename(columns={'Appearance':'Appearance_Team_A'},inplace=True)

    #merge with world cup result data 
    #Includes Team_B Appearance
    World_cup_Appearance_df=pd.merge(World_cup_Appearance_df,Appearance_df,left_on=['Team_B','Year'],right_on=['Team','Year'],how='left')
    World_cup_Appearance_df.drop(axis=1,labels=['Team'],inplace=True)
    World_cup_Appearance_df.rename(columns={'Appearance':'Appearance_Team_B'},inplace=True)
    
    return (World_cup_Appearance_df)

In [45]:
def missing_value_imputation():
    #Missing imputation using 0 for attributes which is NA as they have not played before

    World_cup_final_data.No_of_match_head_2_head_wc.fillna(0,inplace=True)
    World_cup_final_data.Team_A_head2head_win_wc.fillna(0,inplace=True)
    World_cup_final_data.Team_B_head2head_win_wc.fillna(0,inplace=True)
    World_cup_final_data.Draw_wc.fillna(0,inplace=True)

    World_cup_final_data.No_of_match_head_2_head_all.fillna(0,inplace=True)
    World_cup_final_data.Team_A_head2head_win_all_match.fillna(0,inplace=True)
    World_cup_final_data.Team_B_head2head_win_all_match.fillna(0,inplace=True)
    World_cup_final_data.Draw_all_match.fillna(0,inplace=True)

    World_cup_final_data.No_of_match_head_2_head_all_10yr.fillna(0,inplace=True)
    World_cup_final_data.Team_A_win_all_match_10yr.fillna(0,inplace=True)
    World_cup_final_data.Team_B_win_all_match_10yr.fillna(0,inplace=True)
    World_cup_final_data.Draw_all_match_10yr.fillna(0,inplace=True)

    World_cup_final_data.Team_A_all_match_win.fillna(0,inplace=True)
    World_cup_final_data.Team_A_all_match_Draw.fillna(0,inplace=True)
    World_cup_final_data.Team_B_all_match_win.fillna(0,inplace=True)
    World_cup_final_data.Team_B_all_match_Draw.fillna(0,inplace=True)

    World_cup_final_data.Team_A_wc_win.fillna(0,inplace=True)
    World_cup_final_data.Team_A_wc_Draw.fillna(0,inplace=True)
    World_cup_final_data.Team_B_wc_win.fillna(0,inplace=True)
    World_cup_final_data.Team_B_wc_Draw.fillna(0,inplace=True)

    World_cup_final_data.Team_A_last_10_match_win.fillna(0,inplace=True)
    World_cup_final_data.Team_A_last_10_match_Draw.fillna(0,inplace=True)
    World_cup_final_data.Team_B_last_10_match_win.fillna(0,inplace=True)
    World_cup_final_data.Team_B_last_10_match_Draw.fillna(0,inplace=True)

    World_cup_final_data['Rank_Team_A']=World_cup_final_data.groupby(["Year","Team_A"]).transform(lambda x: x.fillna(x.mean()))['Rank_Team_A']
    World_cup_final_data['Rank_Team_B']=World_cup_final_data.groupby(["Year","Team_B"]).transform(lambda x: x.fillna(x.mean()))['Rank_Team_B']
    return (World_cup_final_data)

In [46]:
###Create comparative features
def comparative_feature_engineering(World_cup_final_data):
    World_cup_final_data['win_diff_h2h_wc_match'] = World_cup_final_data.Team_A_head2head_win_wc - World_cup_final_data.Team_A_head2head_win_wc
    World_cup_final_data['draw_h2h_wc_per_match'] = World_cup_final_data.Draw_wc/World_cup_final_data.No_of_match_head_2_head_wc

    World_cup_final_data['win_diff_h2h_all_match'] = World_cup_final_data.Team_A_head2head_win_all_match - World_cup_final_data.Team_B_head2head_win_all_match
    World_cup_final_data['draw_h2h_all_per_match'] = World_cup_final_data.Draw_all_match/World_cup_final_data.No_of_match_head_2_head_all
    World_cup_final_data['win_diff_h2h_all_match_percent'] = World_cup_final_data.win_diff_h2h_all_match /World_cup_final_data.No_of_match_head_2_head_all

    World_cup_final_data['win_diff_h2h_all_match_10yr'] = World_cup_final_data.Team_A_win_all_match_10yr - World_cup_final_data.Team_B_win_all_match_10yr
    World_cup_final_data['draw_h2h_all_per_match_10yr'] = World_cup_final_data.Draw_all_match_10yr/World_cup_final_data.No_of_match_head_2_head_all_10yr

    World_cup_final_data['win_percent_diff_wc'] = (World_cup_final_data.Team_A_wc_win/World_cup_final_data.Appearance_Team_A)-(World_cup_final_data.Team_B_wc_win/World_cup_final_data.Appearance_Team_B)
    World_cup_final_data['Draw_percent_diff_wc'] = (World_cup_final_data.Team_A_wc_Draw/World_cup_final_data.Appearance_Team_A)-(World_cup_final_data.Team_B_wc_Draw/World_cup_final_data.Appearance_Team_B)

    World_cup_final_data['win_diff_last_10_match'] = World_cup_final_data.Team_A_last_10_match_win-World_cup_final_data.Team_B_last_10_match_win

    World_cup_final_data['Rank_diff'] = World_cup_final_data.Rank_Team_A - World_cup_final_data.Rank_Team_B

    World_cup_final_data['Appearance_diff'] = World_cup_final_data.Appearance_Team_A - World_cup_final_data.Appearance_Team_B
    return (World_cup_final_data)

In [102]:
##Call all the functions
def feature_engineering_module(x):
    winner_count_Worldcup=wc_h2h_calculation(x)
    winner_count_all_match=all_match_h2h_calculation(x)
    winner_count_all_match.Date = pd.to_datetime(winner_count_all_match.Date)
    winner_count_all_match_last_10_yr=h2h_all_10yrs(x)
    winner_count_all_match_last_10_yr.Date = pd.to_datetime(winner_count_all_match_last_10_yr.Date)
    
    winner_count_team_performance_all_match=team_performance_all_match(x)
    winner_count_team_performance_wc=team_performance_wc_match(x)
    winner_count_team_performance_last_10_match=team_performance_all_match_10yr(x)
    Rank = rank_calculation(x)
    World_cup_Appearance_df = appearance_calculation(x)
    x.Date=x.Date.map(lambda x: np.datetime64(x))
    ##Combine all stats
    World_cup_all_stat_data=pd.merge(pd.merge(pd.merge(pd.merge(pd.merge(pd.merge(pd.merge(pd.merge(x,winner_count_Worldcup,on=['Date','Team_A','Team_B'],how='left'),winner_count_all_match,
         on=['Date','Team_A','Team_B'],how='left'),winner_count_all_match_last_10_yr,on=['Date','Team_A','Team_B'],how='left'),
         winner_count_team_performance_all_match,on=['Date','Team_A','Team_B'],how='left'),winner_count_team_performance_wc,
         on=['Date','Team_A','Team_B'],how='left'),winner_count_team_performance_last_10_match,on=['Date','Team_A','Team_B'],how='left'),
                                 Rank,on=['Month','Year','Team_A','Team_B'],how='left'),World_cup_Appearance_df,on=['Year','Team_A','Team_B'],how='left')
    

    
    World_cup_all_stat_data.drop_duplicates(keep='first',inplace=True)
    
    World_cup_all_stat_data=comparative_feature_engineering(World_cup_all_stat_data)
    
    World_cup_all_stat_data=World_cup_all_stat_data[~World_cup_all_stat_data.Rank_diff.isnull()]
    
    World_cup_all_stat_data.fillna(0,inplace=True)
    
    World_cup_all_stat_data.win_percent_diff_wc=World_cup_all_stat_data.win_percent_diff_wc.map(lambda x: 0 if np.isinf(x) else x)
    World_cup_all_stat_data.Draw_percent_diff_wc=World_cup_all_stat_data.Draw_percent_diff_wc.map(lambda x: 0 if np.isinf(x) else x)
    
    return (World_cup_all_stat_data)

In [103]:
##Create all features
World_cup_final_data = feature_engineering_module(historical_data)

1930-07-13T00:00:00.000000000
1930-07-14T00:00:00.000000000
1930-07-15T00:00:00.000000000
1930-07-16T00:00:00.000000000
1930-07-17T00:00:00.000000000
1930-07-18T00:00:00.000000000
1930-07-19T00:00:00.000000000
1930-07-20T00:00:00.000000000
1930-07-21T00:00:00.000000000
1930-07-22T00:00:00.000000000
1930-07-26T00:00:00.000000000
1930-07-27T00:00:00.000000000
1930-07-30T00:00:00.000000000
1934-05-27T00:00:00.000000000
1934-05-31T00:00:00.000000000
1934-01-06T00:00:00.000000000
1934-03-06T00:00:00.000000000
1934-07-06T00:00:00.000000000
1934-10-06T00:00:00.000000000
1938-04-06T00:00:00.000000000
1938-05-06T00:00:00.000000000
1938-09-06T00:00:00.000000000
1938-12-06T00:00:00.000000000
1938-06-14T00:00:00.000000000
1938-06-16T00:00:00.000000000
1938-06-19T00:00:00.000000000
1950-06-24T00:00:00.000000000
1950-06-25T00:00:00.000000000
1950-06-28T00:00:00.000000000
1950-06-29T00:00:00.000000000
1950-01-07T00:00:00.000000000
1950-02-07T00:00:00.000000000
1950-09-07T00:00:00.000000000
1950-07-13T00:00:00.000000000
1950-07-16T00:00:00.000000000
1954-06-16T00:00:00.000000000
1954-06-17T00:00:00.000000000
1954-06-19T00:00:00.000000000
1954-06-20T00:00:00.000000000
1954-06-23T00:00:00.000000000
1954-06-26T00:00:00.000000000
1954-06-27T00:00:00.000000000
1954-06-30T00:00:00.000000000
1954-03-07T00:00:00.000000000
1954-04-07T00:00:00.000000000
1958-08-06T00:00:00.000000000
1958-11-06T00:00:00.000000000
1958-12-06T00:00:00.000000000
1958-06-15T00:00:00.000000000
1958-06-17T00:00:00.000000000
1958-06-19T00:00:00.000000000
1958-06-24T00:00:00.000000000
1958-06-28T00:00:00.000000000
1958-06-29T00:00:00.000000000
1962-05-30T00:00:00.000000000
1962-05-31T00:00:00.000000000
1962-02-06T00:00:00.000000000
1962-03-06T00:00:00.000000000
1962-06-06T00:00:00.000000000
1962-07-06T00:00:00.000000000
1962-10-06T00:00:00.000000000
1962-06-13T00:00:00.000000000
1962-06-16T00:00:00.000000000
1962-06-17T00:00:00.000000000
1966-11-07T00:00:00.000000000
1966-12-07T00:00:00.000000000
1966-07-13T00:00:00.000000000
1966-07-15T00:00:00.000000000
1966-07-16T00:00:00.000000000
1966-07-19T00:00:00.000000000
1966-07-20T00:00:00.000000000
1966-07-23T00:00:00.000000000
1966-07-25T00:00:00.000000000
1966-07-26T00:00:00.000000000
1966-07-28T00:00:00.000000000
1966-07-30T00:00:00.000000000
1970-05-31T00:00:00.000000000
1970-02-06T00:00:00.000000000
1970-03-06T00:00:00.000000000
1970-06-06T00:00:00.000000000
1970-07-06T00:00:00.000000000
1970-10-06T00:00:00.000000000
1970-11-06T00:00:00.000000000
1970-06-14T00:00:00.000000000
1970-06-17T00:00:00.000000000
1970-06-20T00:00:00.000000000
1970-06-21T00:00:00.000000000
1974-06-13T00:00:00.000000000
1974-06-14T00:00:00.000000000
1974-06-15T00:00:00.000000000
1974-06-18T00:00:00.000000000
1974-06-19T00:00:00.000000000
1974-06-22T00:00:00.000000000
1974-06-23T00:00:00.000000000
1974-06-26T00:00:00.000000000
1974-06-30T00:00:00.000000000
1974-03-07T00:00:00.000000000
1974-06-07T00:00:00.000000000
1974-07-07T00:00:00.000000000
1978-01-06T00:00:00.000000000
1978-02-06T00:00:00.000000000
1978-03-06T00:00:00.000000000
1978-06-06T00:00:00.000000000
1978-07-06T00:00:00.000000000
1978-10-06T00:00:00.000000000
1978-11-06T00:00:00.000000000
1978-06-14T00:00:00.000000000
1978-06-18T00:00:00.000000000
1978-06-21T00:00:00.000000000
1978-06-24T00:00:00.000000000
1978-06-25T00:00:00.000000000
1982-06-13T00:00:00.000000000
1982-06-14T00:00:00.000000000
1982-06-15T00:00:00.000000000
1982-06-16T00:00:00.000000000
1982-06-17T00:00:00.000000000
1982-06-18T00:00:00.000000000
1982-06-19T00:00:00.000000000
1982-06-20T00:00:00.000000000
1982-06-21T00:00:00.000000000
1982-06-22T00:00:00.000000000
1982-06-23T00:00:00.000000000
1982-06-24T00:00:00.000000000
1982-06-25T00:00:00.000000000
1982-06-28T00:00:00.000000000
1982-06-29T00:00:00.000000000
1982-01-07T00:00:00.000000000
1982-02-07T00:00:00.000000000
1982-04-07T00:00:00.000000000
1982-05-07T00:00:00.000000000
1982-08-07T00:00:00.000000000
1982-10-07T00:00:00.000000000
1982-11-07T00:00:00.000000000
1986-05-31T00:00:00.000000000
1986-01-06T00:00:00.000000000
1986-02-06T00:00:00.000000000
1986-03-06T00:00:00.000000000
1986-04-06T00:00:00.000000000
1986-05-06T00:00:00.000000000
1986-06-06T00:00:00.000000000
1986-07-06T00:00:00.000000000
1986-08-06T00:00:00.000000000
1986-09-06T00:00:00.000000000
1986-10-06T00:00:00.000000000
1986-11-06T00:00:00.000000000
1986-12-06T00:00:00.000000000
1986-06-13T00:00:00.000000000
1986-06-15T00:00:00.000000000
1986-06-16T00:00:00.000000000
1986-06-17T00:00:00.000000000
1986-06-18T00:00:00.000000000
1986-06-21T00:00:00.000000000
1986-06-22T00:00:00.000000000
1986-06-25T00:00:00.000000000
1986-06-28T00:00:00.000000000
1986-06-29T00:00:00.000000000
1990-08-06T00:00:00.000000000
1990-09-06T00:00:00.000000000
1990-10-06T00:00:00.000000000
1990-11-06T00:00:00.000000000
1990-12-06T00:00:00.000000000
1990-06-13T00:00:00.000000000
1990-06-14T00:00:00.000000000
1990-06-15T00:00:00.000000000
1990-06-16T00:00:00.000000000
1990-06-17T00:00:00.000000000
1990-06-18T00:00:00.000000000
1990-06-19T00:00:00.000000000
1990-06-20T00:00:00.000000000
1990-06-21T00:00:00.000000000
1990-06-23T00:00:00.000000000
1990-06-24T00:00:00.000000000
1990-06-25T00:00:00.000000000
1990-06-26T00:00:00.000000000
1990-06-30T00:00:00.000000000
1990-01-07T00:00:00.000000000
1990-03-07T00:00:00.000000000
1990-04-07T00:00:00.000000000
1990-07-07T00:00:00.000000000
1990-08-07T00:00:00.000000000
1994-06-17T00:00:00.000000000
1994-06-18T00:00:00.000000000
1994-06-19T00:00:00.000000000
1994-06-20T00:00:00.000000000
1994-06-21T00:00:00.000000000
1994-06-22T00:00:00.000000000
1994-06-23T00:00:00.000000000
1994-06-24T00:00:00.000000000
1994-06-25T00:00:00.000000000
1994-06-26T00:00:00.000000000
1994-06-27T00:00:00.000000000
1994-06-28T00:00:00.000000000
1994-06-29T00:00:00.000000000
1994-06-30T00:00:00.000000000
1994-02-07T00:00:00.000000000
1994-03-07T00:00:00.000000000
1994-04-07T00:00:00.000000000
1994-05-07T00:00:00.000000000
1994-09-07T00:00:00.000000000
1994-10-07T00:00:00.000000000
1994-07-13T00:00:00.000000000
1994-07-16T00:00:00.000000000
1994-07-17T00:00:00.000000000
1998-10-06T00:00:00.000000000
1998-11-06T00:00:00.000000000
1998-12-06T00:00:00.000000000
1998-06-13T00:00:00.000000000
1998-06-14T00:00:00.000000000
1998-06-15T00:00:00.000000000
1998-06-16T00:00:00.000000000
1998-06-17T00:00:00.000000000
1998-06-18T00:00:00.000000000
1998-06-19T00:00:00.000000000
1998-06-20T00:00:00.000000000
1998-06-21T00:00:00.000000000
1998-06-22T00:00:00.000000000
1998-06-23T00:00:00.000000000
1998-06-24T00:00:00.000000000
1998-06-25T00:00:00.000000000
1998-06-26T00:00:00.000000000
1998-06-27T00:00:00.000000000
1998-06-28T00:00:00.000000000
1998-06-29T00:00:00.000000000
1998-06-30T00:00:00.000000000
1998-03-07T00:00:00.000000000
1998-04-07T00:00:00.000000000
1998-07-07T00:00:00.000000000
1998-08-07T00:00:00.000000000
1998-11-07T00:00:00.000000000
1998-12-07T00:00:00.000000000
2002-05-31T00:00:00.000000000
2002-01-06T00:00:00.000000000
2002-02-06T00:00:00.000000000
2002-03-06T00:00:00.000000000
2002-04-06T00:00:00.000000000
2002-05-06T00:00:00.000000000
2002-06-06T00:00:00.000000000
2002-07-06T00:00:00.000000000
2002-08-06T00:00:00.000000000
2002-09-06T00:00:00.000000000
2002-10-06T00:00:00.000000000
2002-11-06T00:00:00.000000000
2002-12-06T00:00:00.000000000
2002-06-13T00:00:00.000000000
2002-06-14T00:00:00.000000000
2002-06-15T00:00:00.000000000
2002-06-16T00:00:00.000000000
2002-06-17T00:00:00.000000000
2002-06-18T00:00:00.000000000
2002-06-21T00:00:00.000000000
2002-06-22T00:00:00.000000000
2002-06-25T00:00:00.000000000
2002-06-26T00:00:00.000000000
2002-06-29T00:00:00.000000000
2002-06-30T00:00:00.000000000
2006-09-06T00:00:00.000000000
2006-10-06T00:00:00.000000000
2006-11-06T00:00:00.000000000
2006-12-06T00:00:00.000000000
2006-06-13T00:00:00.000000000
2006-06-14T00:00:00.000000000
2006-06-15T00:00:00.000000000
2006-06-16T00:00:00.000000000
2006-06-17T00:00:00.000000000
2006-06-18T00:00:00.000000000
2006-06-19T00:00:00.000000000
2006-06-20T00:00:00.000000000
2006-06-21T00:00:00.000000000
2006-06-22T00:00:00.000000000
2006-06-23T00:00:00.000000000
2006-06-24T00:00:00.000000000
2006-06-25T00:00:00.000000000
2006-06-26T00:00:00.000000000
2006-06-27T00:00:00.000000000
2006-06-30T00:00:00.000000000
2006-01-07T00:00:00.000000000
2006-04-07T00:00:00.000000000
2006-05-07T00:00:00.000000000
2006-08-07T00:00:00.000000000
2006-09-07T00:00:00.000000000
2010-11-06T00:00:00.000000000
2010-12-06T00:00:00.000000000
2010-06-13T00:00:00.000000000
2010-06-14T00:00:00.000000000
2010-06-15T00:00:00.000000000
2010-06-16T00:00:00.000000000
2010-06-17T00:00:00.000000000
2010-06-18T00:00:00.000000000

2010-06-19T00:00:00.000000000
2010-06-20T00:00:00.000000000
2010-06-21T00:00:00.000000000
2010-06-22T00:00:00.000000000
2010-06-23T00:00:00.000000000
2010-06-24T00:00:00.000000000
2010-06-25T00:00:00.000000000
2010-06-26T00:00:00.000000000
2010-06-27T00:00:00.000000000
2010-06-28T00:00:00.000000000
2010-06-29T00:00:00.000000000
2010-02-07T00:00:00.000000000
2010-03-07T00:00:00.000000000
2010-06-07T00:00:00.000000000
2010-07-07T00:00:00.000000000
2010-10-07T00:00:00.000000000
2010-11-07T00:00:00.000000000
2014-12-06T00:00:00.000000000
2014-06-13T00:00:00.000000000
2014-06-14T00:00:00.000000000
2014-06-15T00:00:00.000000000
2014-06-16T00:00:00.000000000
2014-06-17T00:00:00.000000000
2014-06-18T00:00:00.000000000
2014-06-19T00:00:00.000000000
2014-06-20T00:00:00.000000000
2014-06-21T00:00:00.000000000
2014-06-22T00:00:00.000000000
2014-06-23T00:00:00.000000000
2014-06-24T00:00:00.000000000
2014-06-25T00:00:00.000000000
2014-06-26T00:00:00.000000000
2014-06-28T00:00:00.000000000
2014-06-29T00:00:00.000000000
2014-06-30T00:00:00.000000000
2014-01-07T00:00:00.000000000
2014-04-07T00:00:00.000000000
2014-05-07T00:00:00.000000000
2014-08-07T00:00:00.000000000
2014-09-07T00:00:00.000000000
2014-12-07T00:00:00.000000000
2014-07-13T00:00:00.000000000
2018-06-14T00:00:00.000000000
2018-06-15T00:00:00.000000000
2018-06-16T00:00:00.000000000
2018-06-17T00:00:00.000000000
2018-06-18T00:00:00.000000000
2018-06-19T00:00:00.000000000
2018-06-20T00:00:00.000000000
2018-06-21T00:00:00.000000000
2018-06-22T00:00:00.000000000
2018-06-23T00:00:00.000000000
2018-06-24T00:00:00.000000000
2018-06-25T00:00:00.000000000
2018-06-26T00:00:00.000000000
2018-06-27T00:00:00.000000000
2018-06-28T00:00:00.000000000
1930-07-13T00:00:00.000000000
1930-07-14T00:00:00.000000000
1930-07-15T00:00:00.000000000
1930-07-16T00:00:00.000000000
1930-07-17T00:00:00.000000000
1930-07-18T00:00:00.000000000
1930-07-19T00:00:00.000000000
1930-07-20T00:00:00.000000000
1930-07-21T00:00:00.000000000
1930-07-22T00:00:00.000000000
1930-07-26T00:00:00.000000000
1930-07-27T00:00:00.000000000
1930-07-30T00:00:00.000000000
1934-05-27T00:00:00.000000000
1934-05-31T00:00:00.000000000
1934-01-06T00:00:00.000000000
1934-03-06T00:00:00.000000000
1934-07-06T00:00:00.000000000
1934-10-06T00:00:00.000000000
1938-04-06T00:00:00.000000000
1938-05-06T00:00:00.000000000
1938-09-06T00:00:00.000000000
1938-12-06T00:00:00.000000000
1938-06-14T00:00:00.000000000
1938-06-16T00:00:00.000000000
1938-06-19T00:00:00.000000000
1950-06-24T00:00:00.000000000
1950-06-25T00:00:00.000000000
1950-06-28T00:00:00.000000000
1950-06-29T00:00:00.000000000
1950-01-07T00:00:00.000000000
1950-02-07T00:00:00.000000000
1950-09-07T00:00:00.000000000
1950-07-13T00:00:00.000000000
1950-07-16T00:00:00.000000000
1954-06-16T00:00:00.000000000
1954-06-17T00:00:00.000000000
1954-06-19T00:00:00.000000000
1954-06-20T00:00:00.000000000
1954-06-23T00:00:00.000000000
1954-06-26T00:00:00.000000000
1954-06-27T00:00:00.000000000
1954-06-30T00:00:00.000000000
1954-03-07T00:00:00.000000000
1954-04-07T00:00:00.000000000
1958-08-06T00:00:00.000000000
1958-11-06T00:00:00.000000000
1958-12-06T00:00:00.000000000
1958-06-15T00:00:00.000000000
1958-06-17T00:00:00.000000000
1958-06-19T00:00:00.000000000
1958-06-24T00:00:00.000000000
1958-06-28T00:00:00.000000000
1958-06-29T00:00:00.000000000
1962-05-30T00:00:00.000000000
1962-05-31T00:00:00.000000000
1962-02-06T00:00:00.000000000
1962-03-06T00:00:00.000000000
1962-06-06T00:00:00.000000000
1962-07-06T00:00:00.000000000
1962-10-06T00:00:00.000000000
1962-06-13T00:00:00.000000000
1962-06-16T00:00:00.000000000
1962-06-17T00:00:00.000000000
1966-11-07T00:00:00.000000000
1966-12-07T00:00:00.000000000
1966-07-13T00:00:00.000000000
1966-07-15T00:00:00.000000000
1966-07-16T00:00:00.000000000
1966-07-19T00:00:00.000000000
1966-07-20T00:00:00.000000000
1966-07-23T00:00:00.000000000
1966-07-25T00:00:00.000000000
1966-07-26T00:00:00.000000000
1966-07-28T00:00:00.000000000
1966-07-30T00:00:00.000000000
1970-05-31T00:00:00.000000000
1970-02-06T00:00:00.000000000
1970-03-06T00:00:00.000000000
1970-06-06T00:00:00.000000000
1970-07-06T00:00:00.000000000
1970-10-06T00:00:00.000000000
1970-11-06T00:00:00.000000000
1970-06-14T00:00:00.000000000
1970-06-17T00:00:00.000000000
1970-06-20T00:00:00.000000000
1970-06-21T00:00:00.000000000
1974-06-13T00:00:00.000000000
1974-06-14T00:00:00.000000000
1974-06-15T00:00:00.000000000
1974-06-18T00:00:00.000000000
1974-06-19T00:00:00.000000000
1974-06-22T00:00:00.000000000
1974-06-23T00:00:00.000000000
1974-06-26T00:00:00.000000000
1974-06-30T00:00:00.000000000
1974-03-07T00:00:00.000000000
1974-06-07T00:00:00.000000000
1974-07-07T00:00:00.000000000
1978-01-06T00:00:00.000000000
1978-02-06T00:00:00.000000000
1978-03-06T00:00:00.000000000
1978-06-06T00:00:00.000000000
1978-07-06T00:00:00.000000000
1978-10-06T00:00:00.000000000
1978-11-06T00:00:00.000000000
1978-06-14T00:00:00.000000000
1978-06-18T00:00:00.000000000
1978-06-21T00:00:00.000000000
1978-06-24T00:00:00.000000000
1978-06-25T00:00:00.000000000
1982-06-13T00:00:00.000000000
1982-06-14T00:00:00.000000000
1982-06-15T00:00:00.000000000
1982-06-16T00:00:00.000000000
1982-06-17T00:00:00.000000000
1982-06-18T00:00:00.000000000
1982-06-19T00:00:00.000000000
1982-06-20T00:00:00.000000000
1982-06-21T00:00:00.000000000
1982-06-22T00:00:00.000000000
1982-06-23T00:00:00.000000000
1982-06-24T00:00:00.000000000
1982-06-25T00:00:00.000000000
1982-06-28T00:00:00.000000000
1982-06-29T00:00:00.000000000
1982-01-07T00:00:00.000000000
1982-02-07T00:00:00.000000000
1982-04-07T00:00:00.000000000
1982-05-07T00:00:00.000000000
1982-08-07T00:00:00.000000000
1982-10-07T00:00:00.000000000
1982-11-07T00:00:00.000000000
1986-05-31T00:00:00.000000000
1986-01-06T00:00:00.000000000
1986-02-06T00:00:00.000000000
1986-03-06T00:00:00.000000000
1986-04-06T00:00:00.000000000
1986-05-06T00:00:00.000000000
1986-06-06T00:00:00.000000000
1986-07-06T00:00:00.000000000
1986-08-06T00:00:00.000000000
1986-09-06T00:00:00.000000000
1986-10-06T00:00:00.000000000
1986-11-06T00:00:00.000000000
1986-12-06T00:00:00.000000000
1986-06-13T00:00:00.000000000
1986-06-15T00:00:00.000000000
1986-06-16T00:00:00.000000000
1986-06-17T00:00:00.000000000
1986-06-18T00:00:00.000000000
1986-06-21T00:00:00.000000000
1986-06-22T00:00:00.000000000
1986-06-25T00:00:00.000000000
1986-06-28T00:00:00.000000000
1986-06-29T00:00:00.000000000
1990-08-06T00:00:00.000000000
1990-09-06T00:00:00.000000000
1990-10-06T00:00:00.000000000
1990-11-06T00:00:00.000000000
1990-12-06T00:00:00.000000000
1990-06-13T00:00:00.000000000
1990-06-14T00:00:00.000000000
1990-06-15T00:00:00.000000000
1990-06-16T00:00:00.000000000
1990-06-17T00:00:00.000000000
1990-06-18T00:00:00.000000000
1990-06-19T00:00:00.000000000
1990-06-20T00:00:00.000000000
1990-06-21T00:00:00.000000000
1990-06-23T00:00:00.000000000
1990-06-24T00:00:00.000000000
1990-06-25T00:00:00.000000000
1990-06-26T00:00:00.000000000
1990-06-30T00:00:00.000000000
1990-01-07T00:00:00.000000000
1990-03-07T00:00:00.000000000
1990-04-07T00:00:00.000000000
1990-07-07T00:00:00.000000000
1990-08-07T00:00:00.000000000
1994-06-17T00:00:00.000000000
1994-06-18T00:00:00.000000000
1994-06-19T00:00:00.000000000
1994-06-20T00:00:00.000000000
1994-06-21T00:00:00.000000000
1994-06-22T00:00:00.000000000
1994-06-23T00:00:00.000000000
1994-06-24T00:00:00.000000000
1994-06-25T00:00:00.000000000
1994-06-26T00:00:00.000000000
1994-06-27T00:00:00.000000000
1994-06-28T00:00:00.000000000
1994-06-29T00:00:00.000000000
1994-06-30T00:00:00.000000000
1994-02-07T00:00:00.000000000
1994-03-07T00:00:00.000000000
1994-04-07T00:00:00.000000000
1994-05-07T00:00:00.000000000
1994-09-07T00:00:00.000000000
1994-10-07T00:00:00.000000000
1994-07-13T00:00:00.000000000
1994-07-16T00:00:00.000000000
1994-07-17T00:00:00.000000000
1998-10-06T00:00:00.000000000
1998-11-06T00:00:00.000000000
1998-12-06T00:00:00.000000000
1998-06-13T00:00:00.000000000
1998-06-14T00:00:00.000000000
1998-06-15T00:00:00.000000000
1998-06-16T00:00:00.000000000
1998-06-17T00:00:00.000000000
1998-06-18T00:00:00.000000000
1998-06-19T00:00:00.000000000
1998-06-20T00:00:00.000000000
1998-06-21T00:00:00.000000000
1998-06-22T00:00:00.000000000
1998-06-23T00:00:00.000000000
1998-06-24T00:00:00.000000000
1998-06-25T00:00:00.000000000
1998-06-26T00:00:00.000000000
1998-06-27T00:00:00.000000000
1998-06-28T00:00:00.000000000
1998-06-29T00:00:00.000000000

1998-06-30T00:00:00.000000000
1998-03-07T00:00:00.000000000
1998-04-07T00:00:00.000000000
1998-07-07T00:00:00.000000000
1998-08-07T00:00:00.000000000
1998-11-07T00:00:00.000000000
1998-12-07T00:00:00.000000000
2002-05-31T00:00:00.000000000
2002-01-06T00:00:00.000000000
2002-02-06T00:00:00.000000000
2002-03-06T00:00:00.000000000
2002-04-06T00:00:00.000000000
2002-05-06T00:00:00.000000000
2002-06-06T00:00:00.000000000
2002-07-06T00:00:00.000000000
2002-08-06T00:00:00.000000000
2002-09-06T00:00:00.000000000
2002-10-06T00:00:00.000000000
2002-11-06T00:00:00.000000000
2002-12-06T00:00:00.000000000
2002-06-13T00:00:00.000000000
2002-06-14T00:00:00.000000000
2002-06-15T00:00:00.000000000
2002-06-16T00:00:00.000000000
2002-06-17T00:00:00.000000000
2002-06-18T00:00:00.000000000
2002-06-21T00:00:00.000000000
2002-06-22T00:00:00.000000000
2002-06-25T00:00:00.000000000
2002-06-26T00:00:00.000000000
2002-06-29T00:00:00.000000000
2002-06-30T00:00:00.000000000
2006-09-06T00:00:00.000000000
2006-10-06T00:00:00.000000000
2006-11-06T00:00:00.000000000
2006-12-06T00:00:00.000000000
2006-06-13T00:00:00.000000000
2006-06-14T00:00:00.000000000
2006-06-15T00:00:00.000000000
2006-06-16T00:00:00.000000000
2006-06-17T00:00:00.000000000
2006-06-18T00:00:00.000000000
2006-06-19T00:00:00.000000000
2006-06-20T00:00:00.000000000
2006-06-21T00:00:00.000000000
2006-06-22T00:00:00.000000000
2006-06-23T00:00:00.000000000
2006-06-24T00:00:00.000000000
2006-06-25T00:00:00.000000000
2006-06-26T00:00:00.000000000
2006-06-27T00:00:00.000000000
2006-06-30T00:00:00.000000000
2006-01-07T00:00:00.000000000
2006-04-07T00:00:00.000000000
2006-05-07T00:00:00.000000000
2006-08-07T00:00:00.000000000
2006-09-07T00:00:00.000000000
2010-11-06T00:00:00.000000000
2010-12-06T00:00:00.000000000
2010-06-13T00:00:00.000000000
2010-06-14T00:00:00.000000000
2010-06-15T00:00:00.000000000
2010-06-16T00:00:00.000000000
2010-06-17T00:00:00.000000000
2010-06-18T00:00:00.000000000
2010-06-19T00:00:00.000000000
2010-06-20T00:00:00.000000000
2010-06-21T00:00:00.000000000
2010-06-22T00:00:00.000000000
2010-06-23T00:00:00.000000000
2010-06-24T00:00:00.000000000
2010-06-25T00:00:00.000000000
2010-06-26T00:00:00.000000000
2010-06-27T00:00:00.000000000
2010-06-28T00:00:00.000000000
2010-06-29T00:00:00.000000000
2010-02-07T00:00:00.000000000
2010-03-07T00:00:00.000000000
2010-06-07T00:00:00.000000000
2010-07-07T00:00:00.000000000
2010-10-07T00:00:00.000000000
2010-11-07T00:00:00.000000000
2014-12-06T00:00:00.000000000
2014-06-13T00:00:00.000000000
2014-06-14T00:00:00.000000000
2014-06-15T00:00:00.000000000
2014-06-16T00:00:00.000000000
2014-06-17T00:00:00.000000000
2014-06-18T00:00:00.000000000
2014-06-19T00:00:00.000000000
2014-06-20T00:00:00.000000000
2014-06-21T00:00:00.000000000
2014-06-22T00:00:00.000000000
2014-06-23T00:00:00.000000000
2014-06-24T00:00:00.000000000
2014-06-25T00:00:00.000000000
2014-06-26T00:00:00.000000000
2014-06-28T00:00:00.000000000
2014-06-29T00:00:00.000000000
2014-06-30T00:00:00.000000000
2014-01-07T00:00:00.000000000
2014-04-07T00:00:00.000000000
2014-05-07T00:00:00.000000000
2014-08-07T00:00:00.000000000
2014-09-07T00:00:00.000000000
2014-12-07T00:00:00.000000000
2014-07-13T00:00:00.000000000
2018-06-14T00:00:00.000000000
2018-06-15T00:00:00.000000000
2018-06-16T00:00:00.000000000
2018-06-17T00:00:00.000000000
2018-06-18T00:00:00.000000000
2018-06-19T00:00:00.000000000
2018-06-20T00:00:00.000000000
2018-06-21T00:00:00.000000000
2018-06-22T00:00:00.000000000
2018-06-23T00:00:00.000000000
2018-06-24T00:00:00.000000000
2018-06-25T00:00:00.000000000
2018-06-26T00:00:00.000000000
2018-06-27T00:00:00.000000000
2018-06-28T00:00:00.000000000
1930-07-13 00:00:00
1930-07-14 00:00:00
1930-07-15 00:00:00
1930-07-16 00:00:00
1930-07-17 00:00:00

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\generic.py:4401: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

1930-07-18 00:00:00
1930-07-19 00:00:00
1930-07-20 00:00:00
1930-07-21 00:00:00
1930-07-22 00:00:00
1930-07-26 00:00:00
1930-07-27 00:00:00
1930-07-30 00:00:00
1934-05-27 00:00:00
1934-05-31 00:00:00
1934-01-06 00:00:00
1934-03-06 00:00:00
1934-07-06 00:00:00
1934-10-06 00:00:00
1938-04-06 00:00:00
1938-05-06 00:00:00
1938-09-06 00:00:00
1938-12-06 00:00:00
1938-06-14 00:00:00
1938-06-16 00:00:00
1938-06-19 00:00:00
1950-06-24 00:00:00
1950-06-25 00:00:00
1950-06-28 00:00:00
1950-06-29 00:00:00
1950-01-07 00:00:00
1950-02-07 00:00:00
1950-09-07 00:00:00
1950-07-13 00:00:00
1950-07-16 00:00:00
1954-06-16 00:00:00
1954-06-17 00:00:00
1954-06-19 00:00:00
1954-06-20 00:00:00
1954-06-23 00:00:00
1954-06-26 00:00:00
1954-06-27 00:00:00
1954-06-30 00:00:00
1954-03-07 00:00:00
1954-04-07 00:00:00
1958-08-06 00:00:00
1958-11-06 00:00:00
1958-12-06 00:00:00
1958-06-15 00:00:00
1958-06-17 00:00:00
1958-06-19 00:00:00
1958-06-24 00:00:00
1958-06-28 00:00:00
1958-06-29 00:00:00
1962-05-30 00:00:00
1962-05-31 00:00:00
1962-02-06 00:00:00
1962-03-06 00:00:00
1962-06-06 00:00:00
1962-07-06 00:00:00
1962-10-06 00:00:00
1962-06-13 00:00:00
1962-06-16 00:00:00
1962-06-17 00:00:00
1966-11-07 00:00:00
1966-12-07 00:00:00
1966-07-13 00:00:00
1966-07-15 00:00:00
1966-07-16 00:00:00
1966-07-19 00:00:00
1966-07-20 00:00:00
1966-07-23 00:00:00
1966-07-25 00:00:00
1966-07-26 00:00:00
1966-07-28 00:00:00
1966-07-30 00:00:00
1970-05-31 00:00:00
1970-02-06 00:00:00
1970-03-06 00:00:00
1970-06-06 00:00:00
1970-07-06 00:00:00
1970-10-06 00:00:00
1970-11-06 00:00:00
1970-06-14 00:00:00
1970-06-17 00:00:00
1970-06-20 00:00:00
1970-06-21 00:00:00
1974-06-13 00:00:00
1974-06-14 00:00:00
1974-06-15 00:00:00
1974-06-18 00:00:00
1974-06-19 00:00:00
1974-06-22 00:00:00
1974-06-23 00:00:00
1974-06-26 00:00:00
1974-06-30 00:00:00
1974-03-07 00:00:00
1974-06-07 00:00:00
1974-07-07 00:00:00
1978-01-06 00:00:00
1978-02-06 00:00:00
1978-03-06 00:00:00
1978-06-06 00:00:00
1978-07-06 00:00:00
1978-10-06 00:00:00
1978-11-06 00:00:00
1978-06-14 00:00:00
1978-06-18 00:00:00
1978-06-21 00:00:00
1978-06-24 00:00:00
1978-06-25 00:00:00
1982-06-13 00:00:00
1982-06-14 00:00:00
1982-06-15 00:00:00
1982-06-16 00:00:00
1982-06-17 00:00:00
1982-06-18 00:00:00
1982-06-19 00:00:00
1982-06-20 00:00:00
1982-06-21 00:00:00
1982-06-22 00:00:00
1982-06-23 00:00:00
1982-06-24 00:00:00
1982-06-25 00:00:00
1982-06-28 00:00:00
1982-06-29 00:00:00
1982-01-07 00:00:00
1982-02-07 00:00:00
1982-04-07 00:00:00
1982-05-07 00:00:00
1982-08-07 00:00:00
1982-10-07 00:00:00
1982-11-07 00:00:00
1986-05-31 00:00:00
1986-01-06 00:00:00
1986-02-06 00:00:00
1986-03-06 00:00:00
1986-04-06 00:00:00
1986-05-06 00:00:00
1986-06-06 00:00:00
1986-07-06 00:00:00
1986-08-06 00:00:00
1986-09-06 00:00:00
1986-10-06 00:00:00
1986-11-06 00:00:00
1986-12-06 00:00:00
1986-06-13 00:00:00
1986-06-15 00:00:00
1986-06-16 00:00:00
1986-06-17 00:00:00
1986-06-18 00:00:00
1986-06-21 00:00:00
1986-06-22 00:00:00
1986-06-25 00:00:00
1986-06-28 00:00:00
1986-06-29 00:00:00
1990-08-06 00:00:00
1990-09-06 00:00:00
1990-10-06 00:00:00
1990-11-06 00:00:00
1990-12-06 00:00:00
1990-06-13 00:00:00
1990-06-14 00:00:00
1990-06-15 00:00:00
1990-06-16 00:00:00
1990-06-17 00:00:00
1990-06-18 00:00:00
1990-06-19 00:00:00
1990-06-20 00:00:00
1990-06-21 00:00:00
1990-06-23 00:00:00
1990-06-24 00:00:00
1990-06-25 00:00:00
1990-06-26 00:00:00
1990-06-30 00:00:00
1990-01-07 00:00:00
1990-03-07 00:00:00
1990-04-07 00:00:00
1990-07-07 00:00:00
1990-08-07 00:00:00
1994-06-17 00:00:00
1994-06-18 00:00:00
1994-06-19 00:00:00
1994-06-20 00:00:00
1994-06-21 00:00:00
1994-06-22 00:00:00
1994-06-23 00:00:00
1994-06-24 00:00:00
1994-06-25 00:00:00
1994-06-26 00:00:00
1994-06-27 00:00:00
1994-06-28 00:00:00
1994-06-29 00:00:00
1994-06-30 00:00:00
1994-02-07 00:00:00
1994-03-07 00:00:00
1994-04-07 00:00:00
1994-05-07 00:00:00
1994-09-07 00:00:00
1994-10-07 00:00:00
1994-07-13 00:00:00
1994-07-16 00:00:00
1994-07-17 00:00:00
1998-10-06 00:00:00
1998-11-06 00:00:00
1998-12-06 00:00:00
1998-06-13 00:00:00
1998-06-14 00:00:00
1998-06-15 00:00:00
1998-06-16 00:00:00
1998-06-17 00:00:00
1998-06-18 00:00:00
1998-06-19 00:00:00
1998-06-20 00:00:00
1998-06-21 00:00:00
1998-06-22 00:00:00
1998-06-23 00:00:00
1998-06-24 00:00:00
1998-06-25 00:00:00
1998-06-26 00:00:00
1998-06-27 00:00:00
1998-06-28 00:00:00
1998-06-29 00:00:00
1998-06-30 00:00:00
1998-03-07 00:00:00
1998-04-07 00:00:00
1998-07-07 00:00:00
1998-08-07 00:00:00
1998-11-07 00:00:00
1998-12-07 00:00:00
2002-05-31 00:00:00
2002-01-06 00:00:00
2002-02-06 00:00:00
2002-03-06 00:00:00
2002-04-06 00:00:00
2002-05-06 00:00:00
2002-06-06 00:00:00
2002-07-06 00:00:00
2002-08-06 00:00:00
2002-09-06 00:00:00
2002-10-06 00:00:00
2002-11-06 00:00:00
2002-12-06 00:00:00
2002-06-13 00:00:00
2002-06-14 00:00:00
2002-06-15 00:00:00
2002-06-16 00:00:00
2002-06-17 00:00:00
2002-06-18 00:00:00
2002-06-21 00:00:00
2002-06-22 00:00:00
2002-06-25 00:00:00
2002-06-26 00:00:00
2002-06-29 00:00:00
2002-06-30 00:00:00
2006-09-06 00:00:00
2006-10-06 00:00:00
2006-11-06 00:00:00
2006-12-06 00:00:00
2006-06-13 00:00:00
2006-06-14 00:00:00
2006-06-15 00:00:00
2006-06-16 00:00:00
2006-06-17 00:00:00
2006-06-18 00:00:00
2006-06-19 00:00:00
2006-06-20 00:00:00
2006-06-21 00:00:00
2006-06-22 00:00:00
2006-06-23 00:00:00
2006-06-24 00:00:00
2006-06-25 00:00:00
2006-06-26 00:00:00
2006-06-27 00:00:00
2006-06-30 00:00:00
2006-01-07 00:00:00
2006-04-07 00:00:00
2006-05-07 00:00:00
2006-08-07 00:00:00
2006-09-07 00:00:00
2010-11-06 00:00:00
2010-12-06 00:00:00
2010-06-13 00:00:00
2010-06-14 00:00:00
2010-06-15 00:00:00
2010-06-16 00:00:00
2010-06-17 00:00:00
2010-06-18 00:00:00
2010-06-19 00:00:00
2010-06-20 00:00:00
2010-06-21 00:00:00
2010-06-22 00:00:00
2010-06-23 00:00:00
2010-06-24 00:00:00
2010-06-25 00:00:00
2010-06-26 00:00:00
2010-06-27 00:00:00
2010-06-28 00:00:00
2010-06-29 00:00:00
2010-02-07 00:00:00
2010-03-07 00:00:00
2010-06-07 00:00:00
2010-07-07 00:00:00
2010-10-07 00:00:00
2010-11-07 00:00:00
2014-12-06 00:00:00
2014-06-13 00:00:00
2014-06-14 00:00:00
2014-06-15 00:00:00
2014-06-16 00:00:00
2014-06-17 00:00:00
2014-06-18 00:00:00
2014-06-19 00:00:00
2014-06-20 00:00:00
2014-06-21 00:00:00
2014-06-22 00:00:00
2014-06-23 00:00:00
2014-06-24 00:00:00
2014-06-25 00:00:00
2014-06-26 00:00:00
2014-06-28 00:00:00
2014-06-29 00:00:00
2014-06-30 00:00:00
2014-01-07 00:00:00
2014-04-07 00:00:00
2014-05-07 00:00:00
2014-08-07 00:00:00
2014-09-07 00:00:00
2014-12-07 00:00:00
2014-07-13 00:00:00
2018-06-14 00:00:00
2018-06-15 00:00:00
2018-06-16 00:00:00
2018-06-17 00:00:00
2018-06-18 00:00:00
2018-06-19 00:00:00
2018-06-20 00:00:00
2018-06-21 00:00:00
2018-06-22 00:00:00
2018-06-23 00:00:00
2018-06-24 00:00:00
2018-06-25 00:00:00
2018-06-26 00:00:00
2018-06-27 00:00:00
2018-06-28 00:00:00
1930-07-13 00:00:00
1930-07-14 00:00:00
1930-07-15 00:00:00
1930-07-16 00:00:00
1930-07-17 00:00:00
1930-07-18 00:00:00
1930-07-19 00:00:00
1930-07-20 00:00:00
1930-07-21 00:00:00
1930-07-22 00:00:00
1930-07-26 00:00:00
1930-07-27 00:00:00
1930-07-30 00:00:00
1934-05-27 00:00:00
1934-05-31 00:00:00
1934-01-06 00:00:00
1934-03-06 00:00:00
1934-07-06 00:00:00
1934-10-06 00:00:00
1938-04-06 00:00:00
1938-05-06 00:00:00
1938-09-06 00:00:00
1938-12-06 00:00:00
1938-06-14 00:00:00
1938-06-16 00:00:00
1938-06-19 00:00:00
1950-06-24 00:00:00
1950-06-25 00:00:00
1950-06-28 00:00:00
1950-06-29 00:00:00
1950-01-07 00:00:00
1950-02-07 00:00:00
1950-09-07 00:00:00
1950-07-13 00:00:00
1950-07-16 00:00:00
1954-06-16 00:00:00
1954-06-17 00:00:00
1954-06-19 00:00:00
1954-06-20 00:00:00
1954-06-23 00:00:00
1954-06-26 00:00:00
1954-06-27 00:00:00
1954-06-30 00:00:00
1954-03-07 00:00:00
1954-04-07 00:00:00
1958-08-06 00:00:00
1958-11-06 00:00:00
1958-12-06 00:00:00
1958-06-15 00:00:00
1958-06-17 00:00:00
1958-06-19 00:00:00
1958-06-24 00:00:00
1958-06-28 00:00:00
1958-06-29 00:00:00
1962-05-30 00:00:00
1962-05-31 00:00:00
1962-02-06 00:00:00
1962-03-06 00:00:00
1962-06-06 00:00:00
1962-07-06 00:00:00
1962-10-06 00:00:00
1962-06-13 00:00:00
1962-06-16 00:00:00
1962-06-17 00:00:00
1966-11-07 00:00:00
1966-12-07 00:00:00
1966-07-13 00:00:00
1966-07-15 00:00:00
1966-07-16 00:00:00
1966-07-19 00:00:00
1966-07-20 00:00:00

1966-07-23 00:00:00
1966-07-25 00:00:00
1966-07-26 00:00:00
1966-07-28 00:00:00
1966-07-30 00:00:00
1970-05-31 00:00:00
1970-02-06 00:00:00
1970-03-06 00:00:00
1970-06-06 00:00:00
1970-07-06 00:00:00
1970-10-06 00:00:00
1970-11-06 00:00:00
1970-06-14 00:00:00
1970-06-17 00:00:00
1970-06-20 00:00:00
1970-06-21 00:00:00
1974-06-13 00:00:00
1974-06-14 00:00:00
1974-06-15 00:00:00
1974-06-18 00:00:00
1974-06-19 00:00:00
1974-06-22 00:00:00
1974-06-23 00:00:00
1974-06-26 00:00:00
1974-06-30 00:00:00
1974-03-07 00:00:00
1974-06-07 00:00:00
1974-07-07 00:00:00
1978-01-06 00:00:00
1978-02-06 00:00:00
1978-03-06 00:00:00
1978-06-06 00:00:00
1978-07-06 00:00:00
1978-10-06 00:00:00
1978-11-06 00:00:00
1978-06-14 00:00:00
1978-06-18 00:00:00
1978-06-21 00:00:00
1978-06-24 00:00:00
1978-06-25 00:00:00
1982-06-13 00:00:00
1982-06-14 00:00:00
1982-06-15 00:00:00
1982-06-16 00:00:00
1982-06-17 00:00:00
1982-06-18 00:00:00
1982-06-19 00:00:00
1982-06-20 00:00:00
1982-06-21 00:00:00
1982-06-22 00:00:00
1982-06-23 00:00:00
1982-06-24 00:00:00
1982-06-25 00:00:00
1982-06-28 00:00:00
1982-06-29 00:00:00
1982-01-07 00:00:00
1982-02-07 00:00:00
1982-04-07 00:00:00
1982-05-07 00:00:00
1982-08-07 00:00:00
1982-10-07 00:00:00
1982-11-07 00:00:00
1986-05-31 00:00:00
1986-01-06 00:00:00
1986-02-06 00:00:00
1986-03-06 00:00:00
1986-04-06 00:00:00
1986-05-06 00:00:00
1986-06-06 00:00:00
1986-07-06 00:00:00
1986-08-06 00:00:00
1986-09-06 00:00:00
1986-10-06 00:00:00
1986-11-06 00:00:00
1986-12-06 00:00:00
1986-06-13 00:00:00
1986-06-15 00:00:00
1986-06-16 00:00:00
1986-06-17 00:00:00
1986-06-18 00:00:00
1986-06-21 00:00:00
1986-06-22 00:00:00
1986-06-25 00:00:00
1986-06-28 00:00:00
1986-06-29 00:00:00
1990-08-06 00:00:00
1990-09-06 00:00:00
1990-10-06 00:00:00
1990-11-06 00:00:00
1990-12-06 00:00:00
1990-06-13 00:00:00
1990-06-14 00:00:00
1990-06-15 00:00:00
1990-06-16 00:00:00
1990-06-17 00:00:00
1990-06-18 00:00:00
1990-06-19 00:00:00
1990-06-20 00:00:00
1990-06-21 00:00:00
1990-06-23 00:00:00
1990-06-24 00:00:00
1990-06-25 00:00:00
1990-06-26 00:00:00
1990-06-30 00:00:00
1990-01-07 00:00:00
1990-03-07 00:00:00
1990-04-07 00:00:00
1990-07-07 00:00:00
1990-08-07 00:00:00
1994-06-17 00:00:00
1994-06-18 00:00:00
1994-06-19 00:00:00
1994-06-20 00:00:00
1994-06-21 00:00:00
1994-06-22 00:00:00
1994-06-23 00:00:00
1994-06-24 00:00:00
1994-06-25 00:00:00
1994-06-26 00:00:00
1994-06-27 00:00:00
1994-06-28 00:00:00
1994-06-29 00:00:00
1994-06-30 00:00:00
1994-02-07 00:00:00
1994-03-07 00:00:00
1994-04-07 00:00:00
1994-05-07 00:00:00
1994-09-07 00:00:00
1994-10-07 00:00:00
1994-07-13 00:00:00
1994-07-16 00:00:00
1994-07-17 00:00:00
1998-10-06 00:00:00
1998-11-06 00:00:00
1998-12-06 00:00:00
1998-06-13 00:00:00
1998-06-14 00:00:00
1998-06-15 00:00:00
1998-06-16 00:00:00
1998-06-17 00:00:00
1998-06-18 00:00:00
1998-06-19 00:00:00
1998-06-20 00:00:00
1998-06-21 00:00:00
1998-06-22 00:00:00
1998-06-23 00:00:00
1998-06-24 00:00:00
1998-06-25 00:00:00
1998-06-26 00:00:00
1998-06-27 00:00:00
1998-06-28 00:00:00
1998-06-29 00:00:00
1998-06-30 00:00:00
1998-03-07 00:00:00
1998-04-07 00:00:00
1998-07-07 00:00:00
1998-08-07 00:00:00
1998-11-07 00:00:00
1998-12-07 00:00:00
2002-05-31 00:00:00
2002-01-06 00:00:00
2002-02-06 00:00:00
2002-03-06 00:00:00
2002-04-06 00:00:00
2002-05-06 00:00:00
2002-06-06 00:00:00
2002-07-06 00:00:00
2002-08-06 00:00:00
2002-09-06 00:00:00
2002-10-06 00:00:00
2002-11-06 00:00:00
2002-12-06 00:00:00
2002-06-13 00:00:00
2002-06-14 00:00:00
2002-06-15 00:00:00
2002-06-16 00:00:00
2002-06-17 00:00:00
2002-06-18 00:00:00
2002-06-21 00:00:00
2002-06-22 00:00:00
2002-06-25 00:00:00
2002-06-26 00:00:00
2002-06-29 00:00:00
2002-06-30 00:00:00
2006-09-06 00:00:00
2006-10-06 00:00:00
2006-11-06 00:00:00
2006-12-06 00:00:00
2006-06-13 00:00:00
2006-06-14 00:00:00
2006-06-15 00:00:00
2006-06-16 00:00:00
2006-06-17 00:00:00
2006-06-18 00:00:00
2006-06-19 00:00:00
2006-06-20 00:00:00
2006-06-21 00:00:00
2006-06-22 00:00:00
2006-06-23 00:00:00
2006-06-24 00:00:00
2006-06-25 00:00:00
2006-06-26 00:00:00
2006-06-27 00:00:00
2006-06-30 00:00:00
2006-01-07 00:00:00
2006-04-07 00:00:00
2006-05-07 00:00:00
2006-08-07 00:00:00
2006-09-07 00:00:00
2010-11-06 00:00:00
2010-12-06 00:00:00
2010-06-13 00:00:00
2010-06-14 00:00:00
2010-06-15 00:00:00
2010-06-16 00:00:00
2010-06-17 00:00:00
2010-06-18 00:00:00
2010-06-19 00:00:00
2010-06-20 00:00:00
2010-06-21 00:00:00
2010-06-22 00:00:00
2010-06-23 00:00:00
2010-06-24 00:00:00
2010-06-25 00:00:00
2010-06-26 00:00:00
2010-06-27 00:00:00
2010-06-28 00:00:00
2010-06-29 00:00:00
2010-02-07 00:00:00
2010-03-07 00:00:00
2010-06-07 00:00:00
2010-07-07 00:00:00
2010-10-07 00:00:00
2010-11-07 00:00:00
2014-12-06 00:00:00
2014-06-13 00:00:00
2014-06-14 00:00:00
2014-06-15 00:00:00
2014-06-16 00:00:00
2014-06-17 00:00:00
2014-06-18 00:00:00
2014-06-19 00:00:00
2014-06-20 00:00:00
2014-06-21 00:00:00
2014-06-22 00:00:00
2014-06-23 00:00:00
2014-06-24 00:00:00
2014-06-25 00:00:00
2014-06-26 00:00:00
2014-06-28 00:00:00
2014-06-29 00:00:00
2014-06-30 00:00:00
2014-01-07 00:00:00
2014-04-07 00:00:00
2014-05-07 00:00:00
2014-08-07 00:00:00
2014-09-07 00:00:00
2014-12-07 00:00:00
2014-07-13 00:00:00
2018-06-14 00:00:00
2018-06-15 00:00:00
2018-06-16 00:00:00
2018-06-17 00:00:00
2018-06-18 00:00:00
2018-06-19 00:00:00
2018-06-20 00:00:00
2018-06-21 00:00:00
2018-06-22 00:00:00
2018-06-23 00:00:00
2018-06-24 00:00:00
2018-06-25 00:00:00
2018-06-26 00:00:00
2018-06-27 00:00:00
2018-06-28 00:00:00
Date              datetime64[ns]
Team                      object
Total_match                int64
all_match_Draw             int64
all_match_win              int64
dtype: object
1930-07-13T00:00:00.000000000
1930-07-14T00:00:00.000000000
1930-07-15T00:00:00.000000000
1930-07-16T00:00:00.000000000
1930-07-17T00:00:00.000000000
1930-07-18T00:00:00.000000000
1930-07-19T00:00:00.000000000
1930-07-20T00:00:00.000000000
1930-07-21T00:00:00.000000000
1930-07-22T00:00:00.000000000
1930-07-26T00:00:00.000000000
1930-07-27T00:00:00.000000000
1930-07-30T00:00:00.000000000
1934-05-27T00:00:00.000000000
1934-05-31T00:00:00.000000000
1934-01-06T00:00:00.000000000
1934-03-06T00:00:00.000000000
1934-07-06T00:00:00.000000000
1934-10-06T00:00:00.000000000
1938-04-06T00:00:00.000000000
1938-05-06T00:00:00.000000000
1938-09-06T00:00:00.000000000
1938-12-06T00:00:00.000000000
1938-06-14T00:00:00.000000000
1938-06-16T00:00:00.000000000
1938-06-19T00:00:00.000000000
1950-06-24T00:00:00.000000000
1950-06-25T00:00:00.000000000
1950-06-28T00:00:00.000000000
1950-06-29T00:00:00.000000000
1950-01-07T00:00:00.000000000
1950-02-07T00:00:00.000000000
1950-09-07T00:00:00.000000000
1950-07-13T00:00:00.000000000
1950-07-16T00:00:00.000000000
1954-06-16T00:00:00.000000000
1954-06-17T00:00:00.000000000
1954-06-19T00:00:00.000000000
1954-06-20T00:00:00.000000000
1954-06-23T00:00:00.000000000
1954-06-26T00:00:00.000000000
1954-06-27T00:00:00.000000000
1954-06-30T00:00:00.000000000
1954-03-07T00:00:00.000000000
1954-04-07T00:00:00.000000000
1958-08-06T00:00:00.000000000
1958-11-06T00:00:00.000000000
1958-12-06T00:00:00.000000000
1958-06-15T00:00:00.000000000
1958-06-17T00:00:00.000000000
1958-06-19T00:00:00.000000000
1958-06-24T00:00:00.000000000
1958-06-28T00:00:00.000000000
1958-06-29T00:00:00.000000000
1962-05-30T00:00:00.000000000
1962-05-31T00:00:00.000000000
1962-02-06T00:00:00.000000000
1962-03-06T00:00:00.000000000
1962-06-06T00:00:00.000000000
1962-07-06T00:00:00.000000000
1962-10-06T00:00:00.000000000
1962-06-13T00:00:00.000000000
1962-06-16T00:00:00.000000000
1962-06-17T00:00:00.000000000
1966-11-07T00:00:00.000000000
1966-12-07T00:00:00.000000000
1966-07-13T00:00:00.000000000
1966-07-15T00:00:00.000000000
1966-07-16T00:00:00.000000000
1966-07-19T00:00:00.000000000
1966-07-20T00:00:00.000000000
1966-07-23T00:00:00.000000000
1966-07-25T00:00:00.000000000
1966-07-26T00:00:00.000000000
1966-07-28T00:00:00.000000000
1966-07-30T00:00:00.000000000
1970-05-31T00:00:00.000000000
1970-02-06T00:00:00.000000000
1970-03-06T00:00:00.000000000
1970-06-06T00:00:00.000000000
1970-07-06T00:00:00.000000000
1970-10-06T00:00:00.000000000
1970-11-06T00:00:00.000000000
1970-06-14T00:00:00.000000000
1970-06-17T00:00:00.000000000
1970-06-20T00:00:00.000000000
1970-06-21T00:00:00.000000000
1974-06-13T00:00:00.000000000
1974-06-14T00:00:00.000000000
1974-06-15T00:00:00.000000000
1974-06-18T00:00:00.000000000
1974-06-19T00:00:00.000000000
1974-06-22T00:00:00.000000000

1974-06-23T00:00:00.000000000
1974-06-26T00:00:00.000000000
1974-06-30T00:00:00.000000000
1974-03-07T00:00:00.000000000
1974-06-07T00:00:00.000000000
1974-07-07T00:00:00.000000000
1978-01-06T00:00:00.000000000
1978-02-06T00:00:00.000000000
1978-03-06T00:00:00.000000000
1978-06-06T00:00:00.000000000
1978-07-06T00:00:00.000000000
1978-10-06T00:00:00.000000000
1978-11-06T00:00:00.000000000
1978-06-14T00:00:00.000000000
1978-06-18T00:00:00.000000000
1978-06-21T00:00:00.000000000
1978-06-24T00:00:00.000000000
1978-06-25T00:00:00.000000000
1982-06-13T00:00:00.000000000
1982-06-14T00:00:00.000000000
1982-06-15T00:00:00.000000000
1982-06-16T00:00:00.000000000
1982-06-17T00:00:00.000000000
1982-06-18T00:00:00.000000000
1982-06-19T00:00:00.000000000
1982-06-20T00:00:00.000000000
1982-06-21T00:00:00.000000000
1982-06-22T00:00:00.000000000
1982-06-23T00:00:00.000000000
1982-06-24T00:00:00.000000000
1982-06-25T00:00:00.000000000
1982-06-28T00:00:00.000000000
1982-06-29T00:00:00.000000000
1982-01-07T00:00:00.000000000
1982-02-07T00:00:00.000000000
1982-04-07T00:00:00.000000000
1982-05-07T00:00:00.000000000
1982-08-07T00:00:00.000000000
1982-10-07T00:00:00.000000000
1982-11-07T00:00:00.000000000
1986-05-31T00:00:00.000000000
1986-01-06T00:00:00.000000000
1986-02-06T00:00:00.000000000
1986-03-06T00:00:00.000000000
1986-04-06T00:00:00.000000000
1986-05-06T00:00:00.000000000
1986-06-06T00:00:00.000000000
1986-07-06T00:00:00.000000000
1986-08-06T00:00:00.000000000
1986-09-06T00:00:00.000000000
1986-10-06T00:00:00.000000000
1986-11-06T00:00:00.000000000
1986-12-06T00:00:00.000000000
1986-06-13T00:00:00.000000000
1986-06-15T00:00:00.000000000
1986-06-16T00:00:00.000000000
1986-06-17T00:00:00.000000000
1986-06-18T00:00:00.000000000
1986-06-21T00:00:00.000000000
1986-06-22T00:00:00.000000000
1986-06-25T00:00:00.000000000
1986-06-28T00:00:00.000000000
1986-06-29T00:00:00.000000000
1990-08-06T00:00:00.000000000
1990-09-06T00:00:00.000000000
1990-10-06T00:00:00.000000000
1990-11-06T00:00:00.000000000
1990-12-06T00:00:00.000000000
1990-06-13T00:00:00.000000000
1990-06-14T00:00:00.000000000
1990-06-15T00:00:00.000000000
1990-06-16T00:00:00.000000000
1990-06-17T00:00:00.000000000
1990-06-18T00:00:00.000000000
1990-06-19T00:00:00.000000000
1990-06-20T00:00:00.000000000
1990-06-21T00:00:00.000000000
1990-06-23T00:00:00.000000000
1990-06-24T00:00:00.000000000
1990-06-25T00:00:00.000000000
1990-06-26T00:00:00.000000000
1990-06-30T00:00:00.000000000
1990-01-07T00:00:00.000000000
1990-03-07T00:00:00.000000000
1990-04-07T00:00:00.000000000
1990-07-07T00:00:00.000000000
1990-08-07T00:00:00.000000000
1994-06-17T00:00:00.000000000
1994-06-18T00:00:00.000000000
1994-06-19T00:00:00.000000000
1994-06-20T00:00:00.000000000
1994-06-21T00:00:00.000000000
1994-06-22T00:00:00.000000000
1994-06-23T00:00:00.000000000
1994-06-24T00:00:00.000000000
1994-06-25T00:00:00.000000000
1994-06-26T00:00:00.000000000
1994-06-27T00:00:00.000000000
1994-06-28T00:00:00.000000000
1994-06-29T00:00:00.000000000
1994-06-30T00:00:00.000000000
1994-02-07T00:00:00.000000000
1994-03-07T00:00:00.000000000
1994-04-07T00:00:00.000000000
1994-05-07T00:00:00.000000000
1994-09-07T00:00:00.000000000
1994-10-07T00:00:00.000000000
1994-07-13T00:00:00.000000000
1994-07-16T00:00:00.000000000
1994-07-17T00:00:00.000000000
1998-10-06T00:00:00.000000000
1998-11-06T00:00:00.000000000
1998-12-06T00:00:00.000000000
1998-06-13T00:00:00.000000000
1998-06-14T00:00:00.000000000
1998-06-15T00:00:00.000000000
1998-06-16T00:00:00.000000000
1998-06-17T00:00:00.000000000
1998-06-18T00:00:00.000000000
1998-06-19T00:00:00.000000000
1998-06-20T00:00:00.000000000
1998-06-21T00:00:00.000000000
1998-06-22T00:00:00.000000000
1998-06-23T00:00:00.000000000
1998-06-24T00:00:00.000000000
1998-06-25T00:00:00.000000000
1998-06-26T00:00:00.000000000
1998-06-27T00:00:00.000000000
1998-06-28T00:00:00.000000000
1998-06-29T00:00:00.000000000
1998-06-30T00:00:00.000000000
1998-03-07T00:00:00.000000000
1998-04-07T00:00:00.000000000
1998-07-07T00:00:00.000000000
1998-08-07T00:00:00.000000000
1998-11-07T00:00:00.000000000
1998-12-07T00:00:00.000000000
2002-05-31T00:00:00.000000000
2002-01-06T00:00:00.000000000
2002-02-06T00:00:00.000000000
2002-03-06T00:00:00.000000000
2002-04-06T00:00:00.000000000
2002-05-06T00:00:00.000000000
2002-06-06T00:00:00.000000000
2002-07-06T00:00:00.000000000
2002-08-06T00:00:00.000000000
2002-09-06T00:00:00.000000000
2002-10-06T00:00:00.000000000
2002-11-06T00:00:00.000000000
2002-12-06T00:00:00.000000000
2002-06-13T00:00:00.000000000
2002-06-14T00:00:00.000000000
2002-06-15T00:00:00.000000000
2002-06-16T00:00:00.000000000
2002-06-17T00:00:00.000000000
2002-06-18T00:00:00.000000000
2002-06-21T00:00:00.000000000
2002-06-22T00:00:00.000000000
2002-06-25T00:00:00.000000000
2002-06-26T00:00:00.000000000
2002-06-29T00:00:00.000000000
2002-06-30T00:00:00.000000000
2006-09-06T00:00:00.000000000
2006-10-06T00:00:00.000000000
2006-11-06T00:00:00.000000000
2006-12-06T00:00:00.000000000
2006-06-13T00:00:00.000000000
2006-06-14T00:00:00.000000000
2006-06-15T00:00:00.000000000
2006-06-16T00:00:00.000000000
2006-06-17T00:00:00.000000000
2006-06-18T00:00:00.000000000
2006-06-19T00:00:00.000000000
2006-06-20T00:00:00.000000000
2006-06-21T00:00:00.000000000
2006-06-22T00:00:00.000000000
2006-06-23T00:00:00.000000000
2006-06-24T00:00:00.000000000
2006-06-25T00:00:00.000000000
2006-06-26T00:00:00.000000000
2006-06-27T00:00:00.000000000
2006-06-30T00:00:00.000000000
2006-01-07T00:00:00.000000000
2006-04-07T00:00:00.000000000
2006-05-07T00:00:00.000000000
2006-08-07T00:00:00.000000000
2006-09-07T00:00:00.000000000
2010-11-06T00:00:00.000000000
2010-12-06T00:00:00.000000000
2010-06-13T00:00:00.000000000
2010-06-14T00:00:00.000000000
2010-06-15T00:00:00.000000000
2010-06-16T00:00:00.000000000
2010-06-17T00:00:00.000000000
2010-06-18T00:00:00.000000000
2010-06-19T00:00:00.000000000
2010-06-20T00:00:00.000000000
2010-06-21T00:00:00.000000000
2010-06-22T00:00:00.000000000
2010-06-23T00:00:00.000000000
2010-06-24T00:00:00.000000000
2010-06-25T00:00:00.000000000
2010-06-26T00:00:00.000000000
2010-06-27T00:00:00.000000000
2010-06-28T00:00:00.000000000
2010-06-29T00:00:00.000000000
2010-02-07T00:00:00.000000000
2010-03-07T00:00:00.000000000
2010-06-07T00:00:00.000000000
2010-07-07T00:00:00.000000000
2010-10-07T00:00:00.000000000
2010-11-07T00:00:00.000000000
2014-12-06T00:00:00.000000000
2014-06-13T00:00:00.000000000
2014-06-14T00:00:00.000000000
2014-06-15T00:00:00.000000000
2014-06-16T00:00:00.000000000
2014-06-17T00:00:00.000000000
2014-06-18T00:00:00.000000000
2014-06-19T00:00:00.000000000
2014-06-20T00:00:00.000000000
2014-06-21T00:00:00.000000000
2014-06-22T00:00:00.000000000
2014-06-23T00:00:00.000000000
2014-06-24T00:00:00.000000000
2014-06-25T00:00:00.000000000
2014-06-26T00:00:00.000000000
2014-06-28T00:00:00.000000000
2014-06-29T00:00:00.000000000
2014-06-30T00:00:00.000000000
2014-01-07T00:00:00.000000000
2014-04-07T00:00:00.000000000
2014-05-07T00:00:00.000000000
2014-08-07T00:00:00.000000000
2014-09-07T00:00:00.000000000
2014-12-07T00:00:00.000000000
2014-07-13T00:00:00.000000000
2018-06-14T00:00:00.000000000
2018-06-15T00:00:00.000000000
2018-06-16T00:00:00.000000000
2018-06-17T00:00:00.000000000
2018-06-18T00:00:00.000000000
2018-06-19T00:00:00.000000000
2018-06-20T00:00:00.000000000
2018-06-21T00:00:00.000000000
2018-06-22T00:00:00.000000000
2018-06-23T00:00:00.000000000
2018-06-24T00:00:00.000000000
2018-06-25T00:00:00.000000000
2018-06-26T00:00:00.000000000
2018-06-27T00:00:00.000000000
2018-06-28T00:00:00.000000000
1930-07-13T00:00:00.000000000
1930-07-14T00:00:00.000000000
1930-07-15T00:00:00.000000000
1930-07-16T00:00:00.000000000
1930-07-17T00:00:00.000000000
1930-07-18T00:00:00.000000000
1930-07-19T00:00:00.000000000
1930-07-20T00:00:00.000000000
1930-07-21T00:00:00.000000000
1930-07-22T00:00:00.000000000
1930-07-26T00:00:00.000000000
1930-07-27T00:00:00.000000000
1930-07-30T00:00:00.000000000
1934-05-27T00:00:00.000000000
1934-05-31T00:00:00.000000000
1934-01-06T00:00:00.000000000
1934-03-06T00:00:00.000000000
1934-07-06T00:00:00.000000000
1934-10-06T00:00:00.000000000
1938-04-06T00:00:00.000000000
1938-05-06T00:00:00.000000000
1938-09-06T00:00:00.000000000
1938-12-06T00:00:00.000000000
1938-06-14T00:00:00.000000000
1938-06-16T00:00:00.000000000
1938-06-19T00:00:00.000000000
1950-06-24T00:00:00.000000000

1950-06-25T00:00:00.000000000
1950-06-28T00:00:00.000000000
1950-06-29T00:00:00.000000000
1950-01-07T00:00:00.000000000
1950-02-07T00:00:00.000000000
1950-09-07T00:00:00.000000000
1950-07-13T00:00:00.000000000
1950-07-16T00:00:00.000000000
1954-06-16T00:00:00.000000000
1954-06-17T00:00:00.000000000
1954-06-19T00:00:00.000000000
1954-06-20T00:00:00.000000000
1954-06-23T00:00:00.000000000
1954-06-26T00:00:00.000000000
1954-06-27T00:00:00.000000000
1954-06-30T00:00:00.000000000
1954-03-07T00:00:00.000000000
1954-04-07T00:00:00.000000000
1958-08-06T00:00:00.000000000
1958-11-06T00:00:00.000000000
1958-12-06T00:00:00.000000000
1958-06-15T00:00:00.000000000
1958-06-17T00:00:00.000000000
1958-06-19T00:00:00.000000000
1958-06-24T00:00:00.000000000
1958-06-28T00:00:00.000000000
1958-06-29T00:00:00.000000000
1962-05-30T00:00:00.000000000
1962-05-31T00:00:00.000000000
1962-02-06T00:00:00.000000000
1962-03-06T00:00:00.000000000
1962-06-06T00:00:00.000000000
1962-07-06T00:00:00.000000000
1962-10-06T00:00:00.000000000
1962-06-13T00:00:00.000000000
1962-06-16T00:00:00.000000000
1962-06-17T00:00:00.000000000
1966-11-07T00:00:00.000000000
1966-12-07T00:00:00.000000000
1966-07-13T00:00:00.000000000
1966-07-15T00:00:00.000000000
1966-07-16T00:00:00.000000000
1966-07-19T00:00:00.000000000
1966-07-20T00:00:00.000000000
1966-07-23T00:00:00.000000000
1966-07-25T00:00:00.000000000
1966-07-26T00:00:00.000000000
1966-07-28T00:00:00.000000000
1966-07-30T00:00:00.000000000
1970-05-31T00:00:00.000000000
1970-02-06T00:00:00.000000000
1970-03-06T00:00:00.000000000
1970-06-06T00:00:00.000000000
1970-07-06T00:00:00.000000000
1970-10-06T00:00:00.000000000
1970-11-06T00:00:00.000000000
1970-06-14T00:00:00.000000000
1970-06-17T00:00:00.000000000
1970-06-20T00:00:00.000000000
1970-06-21T00:00:00.000000000
1974-06-13T00:00:00.000000000
1974-06-14T00:00:00.000000000
1974-06-15T00:00:00.000000000
1974-06-18T00:00:00.000000000
1974-06-19T00:00:00.000000000
1974-06-22T00:00:00.000000000
1974-06-23T00:00:00.000000000
1974-06-26T00:00:00.000000000
1974-06-30T00:00:00.000000000
1974-03-07T00:00:00.000000000
1974-06-07T00:00:00.000000000
1974-07-07T00:00:00.000000000
1978-01-06T00:00:00.000000000
1978-02-06T00:00:00.000000000
1978-03-06T00:00:00.000000000
1978-06-06T00:00:00.000000000
1978-07-06T00:00:00.000000000
1978-10-06T00:00:00.000000000
1978-11-06T00:00:00.000000000
1978-06-14T00:00:00.000000000
1978-06-18T00:00:00.000000000
1978-06-21T00:00:00.000000000
1978-06-24T00:00:00.000000000
1978-06-25T00:00:00.000000000
1982-06-13T00:00:00.000000000
1982-06-14T00:00:00.000000000
1982-06-15T00:00:00.000000000
1982-06-16T00:00:00.000000000
1982-06-17T00:00:00.000000000
1982-06-18T00:00:00.000000000
1982-06-19T00:00:00.000000000
1982-06-20T00:00:00.000000000
1982-06-21T00:00:00.000000000
1982-06-22T00:00:00.000000000
1982-06-23T00:00:00.000000000
1982-06-24T00:00:00.000000000
1982-06-25T00:00:00.000000000
1982-06-28T00:00:00.000000000
1982-06-29T00:00:00.000000000
1982-01-07T00:00:00.000000000
1982-02-07T00:00:00.000000000
1982-04-07T00:00:00.000000000
1982-05-07T00:00:00.000000000
1982-08-07T00:00:00.000000000
1982-10-07T00:00:00.000000000
1982-11-07T00:00:00.000000000
1986-05-31T00:00:00.000000000
1986-01-06T00:00:00.000000000
1986-02-06T00:00:00.000000000
1986-03-06T00:00:00.000000000
1986-04-06T00:00:00.000000000
1986-05-06T00:00:00.000000000
1986-06-06T00:00:00.000000000
1986-07-06T00:00:00.000000000
1986-08-06T00:00:00.000000000
1986-09-06T00:00:00.000000000
1986-10-06T00:00:00.000000000
1986-11-06T00:00:00.000000000
1986-12-06T00:00:00.000000000
1986-06-13T00:00:00.000000000
1986-06-15T00:00:00.000000000
1986-06-16T00:00:00.000000000
1986-06-17T00:00:00.000000000
1986-06-18T00:00:00.000000000
1986-06-21T00:00:00.000000000
1986-06-22T00:00:00.000000000
1986-06-25T00:00:00.000000000
1986-06-28T00:00:00.000000000
1986-06-29T00:00:00.000000000
1990-08-06T00:00:00.000000000
1990-09-06T00:00:00.000000000
1990-10-06T00:00:00.000000000
1990-11-06T00:00:00.000000000
1990-12-06T00:00:00.000000000
1990-06-13T00:00:00.000000000
1990-06-14T00:00:00.000000000
1990-06-15T00:00:00.000000000
1990-06-16T00:00:00.000000000
1990-06-17T00:00:00.000000000
1990-06-18T00:00:00.000000000
1990-06-19T00:00:00.000000000
1990-06-20T00:00:00.000000000
1990-06-21T00:00:00.000000000
1990-06-23T00:00:00.000000000
1990-06-24T00:00:00.000000000
1990-06-25T00:00:00.000000000
1990-06-26T00:00:00.000000000
1990-06-30T00:00:00.000000000
1990-01-07T00:00:00.000000000
1990-03-07T00:00:00.000000000
1990-04-07T00:00:00.000000000
1990-07-07T00:00:00.000000000
1990-08-07T00:00:00.000000000
1994-06-17T00:00:00.000000000
1994-06-18T00:00:00.000000000
1994-06-19T00:00:00.000000000
1994-06-20T00:00:00.000000000
1994-06-21T00:00:00.000000000
1994-06-22T00:00:00.000000000
1994-06-23T00:00:00.000000000
1994-06-24T00:00:00.000000000
1994-06-25T00:00:00.000000000
1994-06-26T00:00:00.000000000
1994-06-27T00:00:00.000000000
1994-06-28T00:00:00.000000000
1994-06-29T00:00:00.000000000
1994-06-30T00:00:00.000000000
1994-02-07T00:00:00.000000000
1994-03-07T00:00:00.000000000
1994-04-07T00:00:00.000000000
1994-05-07T00:00:00.000000000
1994-09-07T00:00:00.000000000
1994-10-07T00:00:00.000000000
1994-07-13T00:00:00.000000000
1994-07-16T00:00:00.000000000
1994-07-17T00:00:00.000000000
1998-10-06T00:00:00.000000000
1998-11-06T00:00:00.000000000
1998-12-06T00:00:00.000000000
1998-06-13T00:00:00.000000000
1998-06-14T00:00:00.000000000
1998-06-15T00:00:00.000000000
1998-06-16T00:00:00.000000000
1998-06-17T00:00:00.000000000
1998-06-18T00:00:00.000000000
1998-06-19T00:00:00.000000000
1998-06-20T00:00:00.000000000
1998-06-21T00:00:00.000000000
1998-06-22T00:00:00.000000000
1998-06-23T00:00:00.000000000
1998-06-24T00:00:00.000000000
1998-06-25T00:00:00.000000000
1998-06-26T00:00:00.000000000
1998-06-27T00:00:00.000000000
1998-06-28T00:00:00.000000000
1998-06-29T00:00:00.000000000
1998-06-30T00:00:00.000000000
1998-03-07T00:00:00.000000000
1998-04-07T00:00:00.000000000
1998-07-07T00:00:00.000000000
1998-08-07T00:00:00.000000000
1998-11-07T00:00:00.000000000
1998-12-07T00:00:00.000000000
2002-05-31T00:00:00.000000000
2002-01-06T00:00:00.000000000
2002-02-06T00:00:00.000000000
2002-03-06T00:00:00.000000000
2002-04-06T00:00:00.000000000
2002-05-06T00:00:00.000000000
2002-06-06T00:00:00.000000000
2002-07-06T00:00:00.000000000
2002-08-06T00:00:00.000000000
2002-09-06T00:00:00.000000000
2002-10-06T00:00:00.000000000
2002-11-06T00:00:00.000000000
2002-12-06T00:00:00.000000000
2002-06-13T00:00:00.000000000
2002-06-14T00:00:00.000000000
2002-06-15T00:00:00.000000000
2002-06-16T00:00:00.000000000
2002-06-17T00:00:00.000000000
2002-06-18T00:00:00.000000000
2002-06-21T00:00:00.000000000
2002-06-22T00:00:00.000000000
2002-06-25T00:00:00.000000000
2002-06-26T00:00:00.000000000
2002-06-29T00:00:00.000000000
2002-06-30T00:00:00.000000000
2006-09-06T00:00:00.000000000
2006-10-06T00:00:00.000000000
2006-11-06T00:00:00.000000000
2006-12-06T00:00:00.000000000
2006-06-13T00:00:00.000000000
2006-06-14T00:00:00.000000000
2006-06-15T00:00:00.000000000
2006-06-16T00:00:00.000000000
2006-06-17T00:00:00.000000000
2006-06-18T00:00:00.000000000
2006-06-19T00:00:00.000000000
2006-06-20T00:00:00.000000000
2006-06-21T00:00:00.000000000
2006-06-22T00:00:00.000000000
2006-06-23T00:00:00.000000000
2006-06-24T00:00:00.000000000
2006-06-25T00:00:00.000000000
2006-06-26T00:00:00.000000000
2006-06-27T00:00:00.000000000
2006-06-30T00:00:00.000000000
2006-01-07T00:00:00.000000000
2006-04-07T00:00:00.000000000
2006-05-07T00:00:00.000000000
2006-08-07T00:00:00.000000000
2006-09-07T00:00:00.000000000
2010-11-06T00:00:00.000000000
2010-12-06T00:00:00.000000000
2010-06-13T00:00:00.000000000
2010-06-14T00:00:00.000000000
2010-06-15T00:00:00.000000000
2010-06-16T00:00:00.000000000
2010-06-17T00:00:00.000000000
2010-06-18T00:00:00.000000000
2010-06-19T00:00:00.000000000
2010-06-20T00:00:00.000000000
2010-06-21T00:00:00.000000000
2010-06-22T00:00:00.000000000
2010-06-23T00:00:00.000000000
2010-06-24T00:00:00.000000000
2010-06-25T00:00:00.000000000
2010-06-26T00:00:00.000000000
2010-06-27T00:00:00.000000000
2010-06-28T00:00:00.000000000
2010-06-29T00:00:00.000000000
2010-02-07T00:00:00.000000000
2010-03-07T00:00:00.000000000
2010-06-07T00:00:00.000000000
2010-07-07T00:00:00.000000000
2010-10-07T00:00:00.000000000
2010-11-07T00:00:00.000000000

2014-12-06T00:00:00.000000000
2014-06-13T00:00:00.000000000
2014-06-14T00:00:00.000000000
2014-06-15T00:00:00.000000000
2014-06-16T00:00:00.000000000
2014-06-17T00:00:00.000000000
2014-06-18T00:00:00.000000000
2014-06-19T00:00:00.000000000
2014-06-20T00:00:00.000000000
2014-06-21T00:00:00.000000000
2014-06-22T00:00:00.000000000
2014-06-23T00:00:00.000000000
2014-06-24T00:00:00.000000000
2014-06-25T00:00:00.000000000
2014-06-26T00:00:00.000000000
2014-06-28T00:00:00.000000000
2014-06-29T00:00:00.000000000
2014-06-30T00:00:00.000000000
2014-01-07T00:00:00.000000000
2014-04-07T00:00:00.000000000
2014-05-07T00:00:00.000000000
2014-08-07T00:00:00.000000000
2014-09-07T00:00:00.000000000
2014-12-07T00:00:00.000000000
2014-07-13T00:00:00.000000000
2018-06-14T00:00:00.000000000
2018-06-15T00:00:00.000000000
2018-06-16T00:00:00.000000000
2018-06-17T00:00:00.000000000
2018-06-18T00:00:00.000000000
2018-06-19T00:00:00.000000000
2018-06-20T00:00:00.000000000
2018-06-21T00:00:00.000000000
2018-06-22T00:00:00.000000000
2018-06-23T00:00:00.000000000
2018-06-24T00:00:00.000000000
2018-06-25T00:00:00.000000000
2018-06-26T00:00:00.000000000
2018-06-27T00:00:00.000000000
2018-06-28T00:00:00.000000000
1930.0
1930.0833333333333
1930.1666666666665
1930.2499999999998
1930.333333333333
1930.4166666666663
1930.4999999999995
1930.5833333333328
1930.666666666666
1930.7499999999993
1930.8333333333326
1930.9166666666658
1930.999999999999
1931.0833333333323
1931.1666666666656
1931.2499999999989
1931.3333333333321
1931.4166666666654
1931.4999999999986
1931.583333333332
1931.6666666666652
1931.7499999999984
1931.8333333333317
1931.916666666665
1931.9999999999982
1932.0833333333314
1932.1666666666647
1932.249999999998
1932.3333333333312
1932.4166666666645
1932.4999999999977
1932.583333333331
1932.6666666666642
1932.7499999999975
1932.8333333333308
1932.916666666664
1932.9999999999973
1933.0833333333305
1933.1666666666638
1933.249999999997
1933.3333333333303
1933.4166666666636
1933.4999999999968
1933.58333333333
1933.6666666666633
1933.7499999999966
1933.8333333333298
1933.916666666663
1933.9999999999964
1934.0833333333296
1934.1666666666629
1934.2499999999961
1934.3333333333294
1934.4166666666626
1934.499999999996
1934.5833333333292
1934.6666666666624
1934.7499999999957
1934.833333333329
1934.9166666666622
1934.9999999999955
1935.0833333333287
1935.166666666662
1935.2499999999952
1935.3333333333285
1935.4166666666617
1935.499999999995
1935.5833333333283
1935.6666666666615
1935.7499999999948
1935.833333333328
1935.9166666666613
1935.9999999999945
1936.0833333333278
1936.166666666661
1936.2499999999943
1936.3333333333276
1936.4166666666608
1936.499999999994
1936.5833333333273
1936.6666666666606
1936.7499999999939
1936.8333333333271
1936.9166666666604
1936.9999999999936
1937.083333333327
1937.1666666666601
1937.2499999999934
1937.3333333333267
1937.41666666666
1937.4999999999932
1937.5833333333264
1937.6666666666597
1937.749999999993
1937.8333333333262
1937.9166666666595
1937.9999999999927
1938.083333333326
1938.1666666666592
1938.2499999999925
1938.3333333333258
1938.416666666659
1938.4999999999923
1938.5833333333255
1938.6666666666588
1938.749999999992
1938.8333333333253
1938.9166666666586
1938.9999999999918
1939.083333333325
1939.1666666666583
1939.2499999999916
1939.3333333333248
1939.416666666658
1939.4999999999914
1939.5833333333246
1939.6666666666579
1939.7499999999911
1939.8333333333244
1939.9166666666576
1939.999999999991
1940.0833333333242
1940.1666666666574
1940.2499999999907
1940.333333333324
1940.4166666666572
1940.4999999999905
1940.5833333333237
1940.666666666657
1940.7499999999902
1940.8333333333235
1940.9166666666567
1940.99999999999
1941.0833333333233
1941.1666666666565
1941.2499999999898
1941.333333333323
1941.4166666666563
1941.4999999999895
1941.5833333333228
1941.666666666656
1941.7499999999893
1941.8333333333226
1941.9166666666558
1941.999999999989
1942.0833333333223
1942.1666666666556
1942.2499999999889
1942.3333333333221
1942.4166666666554
1942.4999999999886
1942.583333333322
1942.6666666666551
1942.7499999999884
1942.8333333333217
1942.916666666655
1942.9999999999882
1943.0833333333214
1943.1666666666547
1943.249999999988
1943.3333333333212
1943.4166666666545
1943.4999999999877
1943.583333333321
1943.6666666666542
1943.7499999999875
1943.8333333333208
1943.916666666654
1943.9999999999873
1944.0833333333205
1944.1666666666538
1944.249999999987
1944.3333333333203
1944.4166666666536
1944.4999999999868
1944.58333333332
1944.6666666666533
1944.7499999999866
1944.8333333333198
1944.916666666653
1944.9999999999864
1945.0833333333196
1945.1666666666529
1945.2499999999861
1945.3333333333194
1945.4166666666526
1945.499999999986
1945.5833333333192
1945.6666666666524
1945.7499999999857
1945.833333333319
1945.9166666666522
1945.9999999999854
1946.0833333333187
1946.166666666652
1946.2499999999852
1946.3333333333185
1946.4166666666517
1946.499999999985
1946.5833333333183
1946.6666666666515
1946.7499999999848
1946.833333333318
1946.9166666666513
1946.9999999999845
1947.0833333333178
1947.166666666651
1947.2499999999843
1947.3333333333176
1947.4166666666508
1947.499999999984
1947.5833333333173
1947.6666666666506
1947.7499999999839
1947.8333333333171
1947.9166666666504
1947.9999999999836
1948.083333333317
1948.1666666666501
1948.2499999999834
1948.3333333333167
1948.41666666665
1948.4999999999832
1948.5833333333164
1948.6666666666497
1948.749999999983
1948.8333333333162
1948.9166666666495
1948.9999999999827
1949.083333333316
1949.1666666666492
1949.2499999999825
1949.3333333333157
1949.416666666649
1949.4999999999823
1949.5833333333155
1949.6666666666488
1949.749999999982
1949.8333333333153
1949.9166666666486
1949.9999999999818
1950.083333333315
1950.1666666666483
1950.2499999999816
1950.3333333333148
1950.416666666648
1950.4999999999814
1950.5833333333146
1950.6666666666479
1950.7499999999811
1950.8333333333144
1950.9166666666476
1950.999999999981
1951.0833333333142
1951.1666666666474
1951.2499999999807
1951.333333333314
1951.4166666666472
1951.4999999999804
1951.5833333333137
1951.666666666647
1951.7499999999802
1951.8333333333135
1951.9166666666467
1951.99999999998
1952.0833333333132
1952.1666666666465
1952.2499999999798
1952.333333333313
1952.4166666666463
1952.4999999999795
1952.5833333333128
1952.666666666646
1952.7499999999793
1952.8333333333126
1952.9166666666458
1952.999999999979
1953.0833333333123
1953.1666666666456
1953.2499999999789
1953.333333333312
1953.4166666666454
1953.4999999999786
1953.5833333333119
1953.6666666666451
1953.7499999999784
1953.8333333333117
1953.916666666645
1953.9999999999782
1954.0833333333114
1954.1666666666447
1954.249999999978
1954.3333333333112
1954.4166666666445
1954.4999999999777
1954.583333333311
1954.6666666666442
1954.7499999999775
1954.8333333333107
1954.916666666644
1954.9999999999773
1955.0833333333105
1955.1666666666438
1955.249999999977
1955.3333333333103
1955.4166666666436
1955.4999999999768
1955.58333333331
1955.6666666666433
1955.7499999999766
1955.8333333333098
1955.916666666643
1955.9999999999764
1956.0833333333096
1956.1666666666429
1956.2499999999761
1956.3333333333094
1956.4166666666426
1956.499999999976
1956.5833333333092
1956.6666666666424
1956.7499999999757
1956.833333333309
1956.9166666666422
1956.9999999999754
1957.0833333333087
1957.166666666642
1957.2499999999752
1957.3333333333085
1957.4166666666417
1957.499999999975
1957.5833333333082
1957.6666666666415
1957.7499999999748
1957.833333333308
1957.9166666666413
1957.9999999999745
1958.0833333333078
1958.166666666641
1958.2499999999743
1958.3333333333076
1958.4166666666408
1958.499999999974
1958.5833333333073
1958.6666666666406
1958.7499999999739
1958.833333333307
1958.9166666666404
1958.9999999999736
1959.0833333333069
1959.1666666666401
1959.2499999999734
1959.3333333333067
1959.41666666664
1959.4999999999732
1959.5833333333064
1959.6666666666397
1959.749999999973
1959.8333333333062
1959.9166666666395
1959.9999999999727
1960.083333333306
1960.1666666666392
1960.2499999999725
1960.3333333333057
1960.416666666639
1960.4999999999723
1960.5833333333055
1960.6666666666388
1960.749999999972
1960.8333333333053
1960.9166666666385
1960.9999999999718
1961.083333333305

1961.1666666666383
1961.2499999999716
1961.3333333333048
1961.416666666638
1961.4999999999714
1961.5833333333046
1961.6666666666379
1961.7499999999711
1961.8333333333044
1961.9166666666376
1961.999999999971
1962.0833333333042
1962.1666666666374
1962.2499999999707
1962.333333333304
1962.4166666666372
1962.4999999999704
1962.5833333333037
1962.666666666637
1962.7499999999702
1962.8333333333035
1962.9166666666367
1962.99999999997
1963.0833333333032
1963.1666666666365
1963.2499999999698
1963.333333333303
1963.4166666666363
1963.4999999999695
1963.5833333333028
1963.666666666636
1963.7499999999693
1963.8333333333026
1963.9166666666358
1963.999999999969
1964.0833333333023
1964.1666666666356
1964.2499999999688
1964.333333333302
1964.4166666666354
1964.4999999999686
1964.5833333333019
1964.6666666666351
1964.7499999999684
1964.8333333333017
1964.916666666635
1964.9999999999682
1965.0833333333014
1965.1666666666347
1965.249999999968
1965.3333333333012
1965.4166666666345
1965.4999999999677
1965.583333333301
1965.6666666666342
1965.7499999999675
1965.8333333333007
1965.916666666634
1965.9999999999673
1966.0833333333005
1966.1666666666338
1966.249999999967
1966.3333333333003
1966.4166666666335
1966.4999999999668
1966.5833333333
1966.6666666666333
1966.7499999999666
1966.8333333332998
1966.916666666633
1966.9999999999663
1967.0833333332996
1967.1666666666329
1967.2499999999661
1967.3333333332994
1967.4166666666326
1967.499999999966
1967.5833333332992
1967.6666666666324
1967.7499999999657
1967.833333333299
1967.9166666666322
1967.9999999999654
1968.0833333332987
1968.166666666632
1968.2499999999652
1968.3333333332985
1968.4166666666317
1968.499999999965
1968.5833333332982
1968.6666666666315
1968.7499999999648
1968.833333333298
1968.9166666666313
1968.9999999999645
1969.0833333332978
1969.166666666631
1969.2499999999643
1969.3333333332976
1969.4166666666308
1969.499999999964
1969.5833333332973
1969.6666666666306
1969.7499999999638
1969.833333333297
1969.9166666666304
1969.9999999999636
1970.0833333332969
1970.1666666666301
1970.2499999999634
1970.3333333332967
1970.41666666663
1970.4999999999632
1970.5833333332964
1970.6666666666297
1970.749999999963
1970.8333333332962
1970.9166666666295
1970.9999999999627
1971.083333333296
1971.1666666666292
1971.2499999999625
1971.3333333332957
1971.416666666629
1971.4999999999623
1971.5833333332955
1971.6666666666288
1971.749999999962
1971.8333333332953
1971.9166666666285
1971.9999999999618
1972.083333333295
1972.1666666666283
1972.2499999999616
1972.3333333332948
1972.416666666628
1972.4999999999613
1972.5833333332946
1972.6666666666279
1972.7499999999611
1972.8333333332944
1972.9166666666276
1972.999999999961
1973.0833333332941
1973.1666666666274
1973.2499999999607
1973.333333333294
1973.4166666666272
1973.4999999999604
1973.5833333332937
1973.666666666627
1973.7499999999602
1973.8333333332935
1973.9166666666267
1973.99999999996
1974.0833333332932
1974.1666666666265
1974.2499999999598
1974.333333333293
1974.4166666666263
1974.4999999999595
1974.5833333332928
1974.666666666626
1974.7499999999593
1974.8333333332926
1974.9166666666258
1974.999999999959
1975.0833333332923
1975.1666666666256
1975.2499999999588
1975.333333333292
1975.4166666666254
1975.4999999999586
1975.5833333332919
1975.6666666666251
1975.7499999999584
1975.8333333332916
1975.916666666625
1975.9999999999582
1976.0833333332914
1976.1666666666247
1976.249999999958
1976.3333333332912
1976.4166666666245
1976.4999999999577
1976.583333333291
1976.6666666666242
1976.7499999999575
1976.8333333332907
1976.916666666624
1976.9999999999573
1977.0833333332905
1977.1666666666238
1977.249999999957
1977.3333333332903
1977.4166666666235
1977.4999999999568
1977.58333333329
1977.6666666666233
1977.7499999999566
1977.8333333332898
1977.916666666623
1977.9999999999563
1978.0833333332896
1978.1666666666229
1978.2499999999561
1978.3333333332894
1978.4166666666226
1978.499999999956
1978.5833333332891
1978.6666666666224
1978.7499999999557
1978.833333333289
1978.9166666666222
1978.9999999999554
1979.0833333332887
1979.166666666622
1979.2499999999552
1979.3333333332885
1979.4166666666217
1979.499999999955
1979.5833333332882
1979.6666666666215
1979.7499999999548
1979.833333333288
1979.9166666666213
1979.9999999999545
1980.0833333332878
1980.166666666621
1980.2499999999543
1980.3333333332876
1980.4166666666208
1980.499999999954
1980.5833333332873
1980.6666666666206
1980.7499999999538
1980.833333333287
1980.9166666666204
1980.9999999999536
1981.0833333332869
1981.1666666666201
1981.2499999999534
1981.3333333332866
1981.41666666662
1981.4999999999532
1981.5833333332864
1981.6666666666197
1981.749999999953
1981.8333333332862
1981.9166666666194
1981.9999999999527
1982.083333333286
1982.1666666666192
1982.2499999999525
1982.3333333332857
1982.416666666619
1982.4999999999523
1982.5833333332855
1982.6666666666188
1982.749999999952
1982.8333333332853
1982.9166666666185
1982.9999999999518
1983.083333333285
1983.1666666666183
1983.2499999999516
1983.3333333332848
1983.416666666618
1983.4999999999513
1983.5833333332846
1983.6666666666179
1983.7499999999511
1983.8333333332844
1983.9166666666176
1983.999999999951
1984.0833333332841
1984.1666666666174
1984.2499999999507
1984.333333333284
1984.4166666666172
1984.4999999999504
1984.5833333332837
1984.666666666617
1984.7499999999502
1984.8333333332835
1984.9166666666167
1984.99999999995
1985.0833333332832
1985.1666666666165
1985.2499999999498
1985.333333333283
1985.4166666666163
1985.4999999999495
1985.5833333332828
1985.666666666616
1985.7499999999493
1985.8333333332826
1985.9166666666158
1985.999999999949
1986.0833333332823
1986.1666666666156
1986.2499999999488
1986.333333333282
1986.4166666666154
1986.4999999999486
1986.5833333332819
1986.6666666666151
1986.7499999999484
1986.8333333332816
1986.916666666615
1986.9999999999482
1987.0833333332814
1987.1666666666147
1987.249999999948
1987.3333333332812
1987.4166666666144
1987.4999999999477
1987.583333333281
1987.6666666666142
1987.7499999999475
1987.8333333332807
1987.916666666614
1987.9999999999472
1988.0833333332805
1988.1666666666138
1988.249999999947
1988.3333333332803
1988.4166666666135
1988.4999999999468
1988.58333333328
1988.6666666666133
1988.7499999999466
1988.8333333332798
1988.916666666613
1988.9999999999463
1989.0833333332796
1989.1666666666129
1989.249999999946
1989.3333333332794
1989.4166666666126
1989.4999999999459
1989.5833333332791
1989.6666666666124
1989.7499999999457
1989.833333333279
1989.9166666666122
1989.9999999999454
1990.0833333332787
1990.166666666612
1990.2499999999452
1990.3333333332785
1990.4166666666117
1990.499999999945
1990.5833333332782
1990.6666666666115
1990.7499999999447
1990.833333333278
1990.9166666666113
1990.9999999999445
1991.0833333332778
1991.166666666611
1991.2499999999443
1991.3333333332776
1991.4166666666108
1991.499999999944
1991.5833333332773
1991.6666666666106
1991.7499999999438
1991.833333333277
1991.9166666666104
1991.9999999999436
1992.0833333332769
1992.1666666666101
1992.2499999999434
1992.3333333332766
1992.41666666661
1992.4999999999432
1992.5833333332764
1992.6666666666097
1992.749999999943
1992.8333333332762
1992.9166666666094
1992.9999999999427
1993.083333333276
1993.1666666666092
1993.2499999999425
1993.3333333332757
1993.416666666609
1993.4999999999422
1993.5833333332755

C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [104]:
World_cup_final_data.tail(48)

,Month,Place,Team_A,Team_B,Team_A_score,Team_B_score,Venue,City,Year,day,...,win_diff_h2h_all_match,draw_h2h_all_per_match,win_diff_h2h_all_match_percent,win_diff_h2h_all_match_10yr,draw_h2h_all_per_match_10yr,win_percent_diff_wc,Draw_percent_diff_wc,win_diff_last_10_match,Rank_diff,Appearance_diff
888,6,Russia,Russia,Saudi-Arabia,0.0,0.0,Luzhniki Stadium,Moscow,2018,14,...,-1,0.000000,-1.000000,0,0.000000,0.068376,0.068376,0.0,-1.0,-4
889,6,Russia,Egypt,Uruguay,0.0,0.0,Nizhny Novgorod Stadium,Nizhny Novgorod,2018,15,...,-1,0.000000,-1.000000,0,0.000000,0.000000,0.000000,1.0,46.0,-47
890,6,Russia,Morocco,Iran,0.0,0.0,Krestovsky Stadium,Saint Petersburg,2018,15,...,0,0.000000,0.000000,0,0.000000,0.070513,0.057692,0.0,6.0,1
891,6,Russia,Portugal,Spain,0.0,0.0,Fisht Olympic Stadium,Sochi,2018,15,...,-4,0.393939,-0.121212,0,0.333333,0.025424,-0.066493,0.0,-4.0,-33
892,6,Russia,France,Australia,0.0,0.0,Kazan Arena,Kazan,2018,16,...,1,0.250000,0.250000,1,0.000000,0.320730,-0.027379,3.0,-33.0,46
893,6,Russia,Argentina,Iceland,0.0,0.0,Otkrytiye Arena,Moscow,2018,16,...,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.0,-17.0,77
894,6,Russia,Peru,Denmark,0.0,0.0,Mordovia Arena,Saransk,2018,16,...,0,0.000000,0.000000,0,0.000000,-0.233333,0.075000,2.0,-1.0,-1
895,6,Russia,Croatia,Nigeria,0.0,0.0,Kaliningrad Stadium,Kaliningrad,2018,16,...,0,0.000000,0.000000,0,0.000000,0.159722,-0.041667,-1.0,-29.0,-2
896,6,Russia,Costa-Rica,Serbia,0.0,0.0,Cosmos Arena,Samara,2018,17,...,0,0.000000,0.000000,0,0.000000,0.000000,0.266667,-3.0,-10.0,12
897,6,Russia,Germany,Mexico,0.0,0.0,Luzhniki Stadium,Moscow,2018,17,...,3,0.444444,0.333333,1,0.000000,0.417667,-0.105060,-1.0,-14.0,-9
898,6,Russia,Brazil,Switzerland,0.0,0.0,Rostov Arena,Rostov-on-Don,2018,17,...,1,0.375000,0.125000,-1,0.000000,0.339744,-0.018357,-2.0,-4.0,71
899,6,Russia,Sweden,South-Korea,0.0,0.0,Nizhny Novgorod Stadium,Nizhny Novgorod,2018,18,...,0,0.000000,0.000000,0,0.000000,0.186536,-0.007714,-2.0,-38.0,15
900,6,Russia,Belgium,Panama,0.0,0.0,Fisht Olympic Stadium,Sochi,2018,18,...,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,4.0,-52.0,41
901,6,Russia,Tunisia,England,0.0,0.0,Volgograd Arena,Volgograd,2018,18,...,0,0.000000,0.000000,0,0.000000,-0.336022,0.010753,-1.0,1.0,-50
902,6,Russia,Russia,Egypt,0.0,0.0,Krestovsky Stadium,Saint Petersburg,2018,19,...,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,-4.0,3.0,5
903,6,Russia,Colombia,Japan,0.0,0.0,Mordovia Arena,Saransk,2018,19,...,0,0.000000,0.000000,1,0.000000,0.153595,-0.124183,0.0,-44.0,1
904,6,Russia,Poland,Senegal,0.0,0.0,Otkrytiye Arena,Moscow,2018,19,...,0,0.000000,0.000000,0,0.000000,0.083871,-0.238710,-1.0,-18.0,26
905,6,Russia,Uruguay,Saudi-Arabia,0.0,0.0,Rostov Arena,Rostov-on-Don,2018,20,...,0,0.000000,0.000000,0,0.000000,0.238311,0.081448,2.0,-50.0,38
906,6,Russia,Portugal,Morocco,0.0,0.0,Luzhniki Stadium,Moscow,2018,20,...,-1,0.000000,-1.000000,0,0.000000,0.346154,-0.153846,1.0,-38.0,13
907,6,Russia,Iran,Spain,0.0,0.0,Kazan Arena,Kazan,2018,20,...,0,0.000000,0.000000,0,0.000000,-0.391243,0.029661,0.0,28.0,-47
908,6,Russia,Denmark,Australia,0.0,0.0,Cosmos Arena,Samara,2018,21,...,1,0.000000,0.333333,0,0.000000,0.346154,-0.105769,2.0,-28.0,3
909,6,Russia,France,Peru,0.0,0.0,Central Stadium,Yekaterinburg,2018,21,...,-1,0.000000,-1.000000,0,0.000000,0.207910,0.003390,0.0,-4.0,44
910,6,Russia,Argentina,Croatia,0.0,0.0,Nizhny Novgorod Stadium,Nizhny Novgorod,2018,21,...,1,0.250000,0.250000,1,0.000000,0.107955,0.056818,1.0,-13.0,61
911,6,Russia,Nigeria,Iceland,0.0,0.0,Volgograd Arena,Volgograd,2018,22,...,-1,0.000000,-1.000000,0,0.000000,0.000000,0.000000,0.0,25.0,18
912,6,Russia,Brazil,Costa-Rica,0.0,0.0,Krestovsky Stadium,Saint Petersburg,2018,22,...,8,0.000000,0.800000,2,0.000000,0.339744,-0.103205,4.0,-23.0,89
913,6,Russia,Serbia,Switzerland,0.0,0.0,Kaliningrad Stadium,Kaliningrad,2018,22,...,0,0.000000,0.000000,0,0.000000,0.000000,-0.181818,-2.0,29.0,-30
914,6,Russia,South-Korea,Mexico,0.0,0.0,Rostov Arena,Rostov-on-Don,2018,23,...,-3,0.181818,-0.272727,-1,0.000000,-0.102861,0.026172,0.0,46.0,-22
915,6,Russia,Germany,Sweden,0.0,0.0,Fisht Olympic Stadium,Sochi,2018,23,...,5,0.300000,0.166667,0,0.000000,0.333992,-0.123518,1.0,-22.0,-2
916,6,Russia,Belgium,Tunisia,0.0,0.0,Otkrytiye Arena,Moscow,2018,23,...,0,0.333333,0.000000,1,0.000000,0.258130,-0.113821,3.0,-11.0,29
917,6,Russia,England,Panama,0.0,0.0,Nizhny Novgorod Stadium,Nizhny Novgorod,2018,24,...,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,1.0,-42.0,62
918,6,Russia,Japan,Senegal,0.0,0.0,Central Stadium,Yekaterinburg,2018,24,...,0,0.000000,0.000000,0,0.000000,-0.164706,-0.164706,-4.0,32.0,12
919,6,Russia,Poland,Colombia,0.0,0.0,Kazan Arena,Kazan,2018,24,...,-1,0.000000,-0.200000,0,0.000000,0.094982,0.050179,3.0,-6.0,13
920,6,Russia,Uruguay,Russia,0.0,0.0,Cosmos Arena,Samara,2018,25,...,0,0.000000,0.000000,0,0.000000,0.169935,0.013072,2.0,-49.0,42
921,6,Russia,Saudi-Arabia,Egypt,0.0,0.0,Volgograd Arena,Volgograd,2018,25,...,-2,0.333333,-0.333333,0,0.000000,0.000000,0.000000,-2.0,4.0,9
922,6,Russia,Iran,Portugal,0.0,0.0,Mordovia Arena,Saransk,2018,25,...,-2,0.000000,-1.000000,0,0.000000,-0.416667,0.096154,-1.0,32.0,-14
923,6,Russia,Spain,Morocco,0.0,0.0,Kaliningrad Stadium,Kaliningrad,2018,25,...,2,0.000000,1.000000,0,0.000000,0.320730,-0.087353,0.0,-34.0,46
924,6,Russia,Denmark,France,0.0,0.0,Luzhniki Stadium,Moscow,2018,26,...,-4,0.076923,-0.307692,-2,0.000000,0.025424,-0.078390,-1.0,5.0,-43
925,6,Russia,Australia,Peru,0.0,0.0,Fisht Olympic Stadium,Sochi,2018,26,...,0,0.000000,0.000000,0,0.000000,-0.112821,0.030769,-2.0,29.0,-2
926,6,Russia,Nigeria,Argentina,0.0,0.0,Krestovsky Stadium,Saint Petersburg,2018,26,...,-3,0.125000,-0.375000,-1,0.000000,-0.267677,-0.015152,-2.0,42.0,-59
927,6,Russia,Iceland,Croatia,0.0,0.0,Rostov Arena,Rostov-on-Don,2018,26,...,-3,0.166667,-0.500000,-1,0.250000,0.000000,0.000000,1.0,4.0,-16
928,6,Russia,Serbia,Brazil,0.0,0.0,Otkrytiye Arena,Moscow,2018,27,...,0,0.000000,0.000000,-1,0.000000,-0.339744,-0.163462,-2.0,33.0,-101
929,6,Russia,Switzerland,Costa-Rica,0.0,0.0,Nizhny Novgorod Stadium,Nizhny Novgorod,2018,27,...,0,0.000000,0.000000,-1,0.000000,0.000000,-0.084848,5.0,-19.0,18
930,6,Russia,South-Korea,Germany,0.0,0.0,Kazan Arena,Kazan,2018,27,...,-1,0.000000,-0.333333,0,0.000000,-0.520528,0.131232,0.0,60.0,-13
931,6,Russia,Mexico,Sweden,0.0,0.0,Central Stadium,Yekaterinburg,2018,27,...,-2,0.333333,-0.222222,-1,0.000000,-0.083675,-0.018458,2.0,-8.0,7
932,6,Russia,Japan,Poland,0.0,0.0,Volgograd Arena,Volgograd,2018,28,...,-2,0.000000,-0.333333,0,0.000000,-0.248577,0.074004,-3.0,50.0,-14
933,6,Russia,Senegal,Colombia,0.0,0.0,Cosmos Arena,Samara,2018,28,...,0,0.000000,0.000000,0,0.000000,0.011111,0.288889,3.0,12.0,-13
934,6,Russia,Panama,Tunisia,0.0,0.0,Mordovia Arena,Saransk,2018,28,...,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,-1.0,41.0,-12
935,6,Russia,England,Belgium,0.0,0.0,Kaliningrad Stadium,Kaliningrad,2018,28,...,12,0.222222,0.666667,1,0.000000,0.077891,0.103068,-4.0,10.0,21

In [105]:
##Missing Value 
World_cup_final_data.isnull().sum()

Month                               0
Place                               0
Team_A                              0
Team_B                              0
Team_A_score                        0
Team_B_score                        0
Venue                               0
City                                0
Year                                0
day                                 0
Date                                0
Round                               0
Winner_Team                         0
Winner                              0
rest                                0
No_of_match_head_2_head_wc          0
Team_A_head2head_win_wc             0
Team_B_head2head_win_wc             0
Draw_wc                             0
No_of_match_head_2_head_all         0
Team_A_head2head_win_all_match      0
Team_B_head2head_win_all_match      0
Draw_all_match                      0
No_of_match_head_2_head_all_10yr    0
Team_A_win_all_match_10yr           0
Team_B_win_all_match_10yr           0
Draw_all_match_10yr                 0
Team_A_all_match_win                0
Team_A_all_match_Draw               0
Team_B_all_match_win                0
Team_B_all_match_Draw               0
Team_A_wc_win                       0
Team_A_wc_Draw                      0
Team_B_wc_win                       0
Team_B_wc_Draw                      0
Team_A_last_10_match_win            0
Team_A_last_10_match_Draw           0
Team_B_last_10_match_win            0
Team_B_last_10_match_Draw           0
Rank_Team_A                         0
Rank_Team_B                         0
Appearance_Team_A                   0
Appearance_Team_B                   0
win_diff_h2h_wc_match               0
draw_h2h_wc_per_match               0
win_diff_h2h_all_match              0
draw_h2h_all_per_match              0
win_diff_h2h_all_match_percent      0
win_diff_h2h_all_match_10yr         0
draw_h2h_all_per_match_10yr         0
win_percent_diff_wc                 0
Draw_percent_diff_wc                0
win_diff_last_10_match              0
Rank_diff                           0
Appearance_diff                     0
dtype: int64

In [106]:
Final_Cleaned_data = World_cup_final_data[['Month','Year','Place','City','Date',
                                                             'Round','Team_A','Team_B','win_diff_h2h_wc_match',
                                                             'draw_h2h_wc_per_match', 'win_diff_h2h_all_match',
                                                             'draw_h2h_all_per_match', 'win_diff_h2h_all_match_percent',
                                                             'win_diff_h2h_all_match_10yr', 'draw_h2h_all_per_match_10yr',
                                                             'win_percent_diff_wc', 'Draw_percent_diff_wc',
                                                             'win_diff_last_10_match','Rank_diff', 'Appearance_diff','Winner']]

In [107]:
Current_worldcup_data=Final_Cleaned_data[Final_Cleaned_data.Year>2014]
Current_worldcup_data.shape

(48, 21)

In [108]:
Model_data_selected_features=Final_Cleaned_data[World_cup_final_data.Year<=2014]
Model_data_selected_features.shape

(680, 21)

In [109]:
Final_Cleaned_data.to_csv("D:\\Data Science\\World Cup\\Model_data_selected_features.csv")

In [110]:
Current_worldcup_data.to_csv("D:\\Data Science\\World Cup\\Current_worldcup_data.csv")

# Model fitting starts here..............

In [111]:
wc_data=pd.read_csv("D:\\Data Science\\World Cup\\Model_data_selected_features.csv",index_col=0)

In [112]:
###Consider data from 1950 
wc_data=wc_data[wc_data.Year>=1950]

In [113]:
##Create dummy variable for round

dummies_Round_df = pd.get_dummies(wc_data['Round'],prefix='Round_')#.rename(columns=lambda x: 'Round_' + str(x)))
wc_data_incld_dummies_Round = pd.concat([wc_data, dummies_Round_df], axis=1)
wc_data_incld_dummies_Round.drop(['Round'], inplace=True, axis=1)

##Create dummy variable for Team_A
dummies_Team_A = pd.get_dummies(wc_data['Team_A'],prefix='Team_A_')
wc_data_incld_dummies_Team_A = pd.concat([wc_data_incld_dummies_Round, dummies_Team_A], axis=1)
wc_data_incld_dummies_Team_A.drop(['Team_A'], inplace=True, axis=1)

##Create dummy variable for Team_B
dummies_Team_B = pd.get_dummies(wc_data['Team_B'],prefix='Team_B_')
wc_data_incld_dummies_Team_B = pd.concat([wc_data_incld_dummies_Team_A, dummies_Team_B], axis=1)
wc_data_incld_dummies_Team_B.drop(['Team_B'], inplace=True, axis=1)

In [114]:
var_to_use_in_model=['win_diff_h2h_wc_match','draw_h2h_wc_per_match','win_diff_h2h_all_match','draw_h2h_all_per_match','win_diff_h2h_all_match_percent','win_diff_h2h_all_match_10yr','draw_h2h_all_per_match_10yr','win_percent_diff_wc','Draw_percent_diff_wc','win_diff_last_10_match','Rank_diff','Appearance_diff']
dummies_Round_col=wc_data_incld_dummies_Round.columns[wc_data_incld_dummies_Round.columns.str.startswith('Round')].values.tolist()
#dummies_Year=wc_data_incld_dummies_Year.columns[wc_data_incld_dummies_Year.columns.str.startswith('Year')].values.tolist()
dummies_Team_A_col=wc_data_incld_dummies_Team_A.columns[wc_data_incld_dummies_Team_A.columns.str.startswith('Team')].values.tolist()
dummies_Team_B_col=wc_data_incld_dummies_Team_B.columns[wc_data_incld_dummies_Team_B.columns.str.startswith('Team')].values.tolist()
var_to_use_in_model=np.append(np.append(np.append(var_to_use_in_model,dummies_Round_col),dummies_Team_A_col),dummies_Team_B_col)
target = 'Winner'

In [115]:
var_to_use_in_model=['win_diff_h2h_wc_match','draw_h2h_wc_per_match','win_diff_h2h_all_match','draw_h2h_all_per_match','win_diff_h2h_all_match_percent','win_diff_h2h_all_match_10yr','draw_h2h_all_per_match_10yr','win_percent_diff_wc','Draw_percent_diff_wc','win_diff_last_10_match','Rank_diff','Appearance_diff']
#var_to_use_in_model=['Rank_diff','Appearance_diff']

In [116]:
##Train-Test split
def train_test_split(df,var_x,var_y):
    x_train = df[df.Year<2014]
    var_x_train=list(set(x_train.columns) & set(var_x))
    x_train= x_train[var_x_train]
    y_train = df[df.Year<2014][target]
    x_test =df[df.Year==2014]
    var_x_test=list(set(x_test.columns) & set(var_x))
    x_test =x_test[var_x_test]
    y_test = df[df.Year==2014][target]
    return (x_train,y_train,x_test,y_test)

In [117]:
x_train,y_train,x_test,y_test = train_test_split(wc_data_incld_dummies_Team_B,var_to_use_in_model,target)
#x_train,y_train,x_test,y_test = train_test_split(wc_data,var_to_use_in_model,target)

In [118]:
features = pd.DataFrame()
features['feature'] = x_train.columns

In [119]:
##Scaling data
scaler = preprocessing.MinMaxScaler().fit(x_train)
x_train=scaler.transform(x_train)        
x_test=scaler.transform(x_test)

In [120]:
# save the model to disk
filename = 'D:\\Data Science\\World Cup\\scaling_model.sav'
pickle.dump(scaler, open(filename, 'wb'))

In [121]:
##Calculate feature importance
clf = ExtraTreesClassifier(n_estimators=200)
clf = clf.fit(x_train, y_train)


features['importance'] = clf.feature_importances_
features.sort_values(['importance'],ascending=False)

                           feature  importance
7                  Appearance_diff    0.198310
6                        Rank_diff    0.183787
2           win_diff_last_10_match    0.126309
11            Draw_percent_diff_wc    0.120197
9              win_percent_diff_wc    0.114719
3           win_diff_h2h_all_match    0.061970
0      win_diff_h2h_all_match_10yr    0.061298
4   win_diff_h2h_all_match_percent    0.059834
1           draw_h2h_all_per_match    0.049136
5      draw_h2h_all_per_match_10yr    0.018940
8            draw_h2h_wc_per_match    0.005501
10           win_diff_h2h_wc_match    0.000000

In [122]:
#Select only important features
model = SelectFromModel(clf, prefit=True)
x_train_new = model.transform(x_train)
x_train_new.shape
x_test_new = model.transform(x_test)
x_test_new.shape

(61, 5)

In [123]:
##Use all features either one of this or above will be executed
x_train_new=x_train
x_test_new=x_test

In [124]:
##Fit logistic regression
clf = LogisticRegression(multi_class='multinomial', solver='newton-cg')
clf.fit(x_train_new,y_train)
y_pred=clf.predict(x_test_new)

In [125]:
##Fit Random Forest classification
clf = RandomForestClassifier(n_estimators=1000, max_depth=None,min_samples_split=2,max_features='sqrt', random_state=0,oob_score=True)
clf.fit(x_train_new,y_train)
y_pred=clf.predict(x_test_new)

In [225]:
##Fit Random Forest classification
clf = svm.SVC(gamma='auto', kernel='rbf',decision_function_shape='ovo')
clf.fit(x_train_new,y_train)
y_pred=clf.predict(x_test_new)

In [226]:
clf = GradientBoostingClassifier(n_estimators=500, learning_rate=0.01,max_depth=3, random_state=0)
clf.fit(x_train_new, y_train)
y_pred=clf.predict(x_test_new)

In [126]:
clf.score(x_train_new,y_train)

1.0

In [127]:
clf.score(x_test_new,y_test)

0.5081967213114754

In [128]:
confusion_matrix(y_pred,y_test,labels=["Team_A","Draw","Team_B"])

array([[20,  8, 12],
       [ 3,  2,  2],
       [ 2,  3,  9]], dtype=int64)

In [129]:
# save the model to disk
filename = 'D:\\Data Science\\World Cup\\finalized_model.sav'
pickle.dump(clf, open(filename, 'wb'))

# Prediction for latest worldcup starts here

In [449]:
Current_worldcup_data=pd.read_csv("D:\\Data Science\\World Cup\\Current_worldcup_data.csv",index_col=0)
Current_worldcup_data.Date = pd.to_datetime(Current_worldcup_data.Date)

##Read Historical data
Model_data_selected_features=pd.read_csv("D:\\Data Science\\World Cup\\Model_data_selected_features.csv",index_col=0)


historical_data=Model_data_selected_features.append(Current_worldcup_data)

Current_worldcup_data.tail()

,Month,Year,Place,City,Date,Round,Team_A,Team_B,win_diff_h2h_wc_match,draw_h2h_wc_per_match,...,draw_h2h_all_per_match,win_diff_h2h_all_match_percent,win_diff_h2h_all_match_10yr,draw_h2h_all_per_match_10yr,win_percent_diff_wc,Draw_percent_diff_wc,win_diff_last_10_match,Rank_diff,Appearance_diff,Winner
931,6,2018,Russia,Yekaterinburg,2018-06-27,Group,Mexico,Sweden,0,0.0,...,0.333333,-0.222222,-1,0.0,-0.083675,-0.018458,2.0,-8.0,7,Team_B
932,6,2018,Russia,Volgograd,2018-06-28,Group,Japan,Poland,0,0.0,...,0.000000,-0.333333,0,0.0,-0.248577,0.074004,-3.0,50.0,-14,Team_B
933,6,2018,Russia,Samara,2018-06-28,Group,Senegal,Colombia,0,0.0,...,0.000000,0.000000,0,0.0,0.011111,0.288889,3.0,12.0,-13,Team_B
934,6,2018,Russia,Saransk,2018-06-28,Group,Panama,Tunisia,0,0.0,...,0.000000,0.000000,0,0.0,0.000000,0.000000,-1.0,41.0,-12,0
935,6,2018,Russia,Kaliningrad,2018-06-28,Group,England,Belgium,0,0.0,...,0.222222,0.666667,1,0.0,0.077891,0.103068,-4.0,10.0,21,0

In [450]:
# load the model from disk
filename = 'D:\\Data Science\\World Cup\\finalized_model.sav'
clf = pickle.load(open(filename, 'rb'))

# Scaling parameter
filename = 'D:\\Data Science\\World Cup\\scaling_model.sav'
scaler = pickle.load(open(filename, 'rb'))

In [451]:
fixture_all_match=pd.read_csv("D:\\Data Science\\World Cup\\fixtures.csv")
fixture_all_match.head()

#Create Year column 
fixture_all_match['Date']=fixture_all_match.Date.map(lambda x: x.split(" ")[0])
fixture_all_match.Date = pd.to_datetime(fixture_all_match.Date,format="%d-%m-%Y")
fixture_all_match['Month']=fixture_all_match.Date.map(lambda x: x.month)
fixture_all_match.Month = pd.to_numeric(fixture_all_match.Month)
fixture_all_match['Year']=fixture_all_match.Date.map(lambda x: x.year)
fixture_all_match.Year = pd.to_numeric(fixture_all_match.Year)

fixture_all_match.rename(columns={'Home Team': 'Team_A','Away Team': 'Team_B' },inplace=True)

In [452]:
def prediction_function(x,match_round):
    
    ##Predict for Group Stage
    Group_Stage_matches=x[x.Round==match_round]
    var_to_use_in_model=['win_diff_h2h_wc_match','draw_h2h_wc_per_match','win_diff_h2h_all_match','draw_h2h_all_per_match','win_diff_h2h_all_match_percent','win_diff_h2h_all_match_10yr','draw_h2h_all_per_match_10yr','win_percent_diff_wc','Draw_percent_diff_wc','win_diff_last_10_match','Rank_diff','Appearance_diff']
    #var_to_use_in_model=['Rank_diff','Appearance_diff']
    Group_Stage_matches_var = Group_Stage_matches[var_to_use_in_model]

    Group_Stage_matches_var.fillna(0,inplace=True)

    Eval_data=scaler.transform(Group_Stage_matches_var)

    result_prob=pd.DataFrame(clf.predict_proba(Eval_data))
    result_prob.columns = [s + '_prob' for s in clf.classes_]

    Group_Stage_matches['Winner']=clf.predict(Eval_data)

    Group_Stage_matches=pd.concat([Group_Stage_matches.reset_index(drop=True),result_prob],axis=1)

    fixture=pd.merge(fixture_all_match.reset_index(drop=True),Group_Stage_matches[['Date','Team_A','Team_B','Winner','Draw_prob','Team_A_prob','Team_B_prob']],on=['Date','Team_A','Team_B'],how='right')

    def result_calc(x):
        if x.Winner=="Team_A":
            x.Result=x['Team_A']
        elif  x.Winner=="Team_B":
            x.Result=x['Team_B']
        elif x.Winner=="Draw":
            x.Result="Draw"
        return (x.Result)

    fixture.Result=fixture.apply(result_calc,axis=1)

    return fixture

In [453]:
##Group League match prediction
fixture=prediction_function(Current_worldcup_data,"Group")

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\frame.py:3787: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

In [454]:
def score_calc(x):
    
    team_list_2018=pd.Series(np.append(x.Team_A.unique(),x.Team_B.unique()))
    team_score=[]
    for team in team_list_2018.unique():
        df1=x[x.Team_A==team] 
        df2 = x[x.Team_B==team] 
        score1 = sum(df1.Team_A_prob*3 + df1.Draw_prob*1)
        score2 = sum(df2.Team_B_prob*3 + df2.Draw_prob*1)
        total_score = score1+score2
        team_score.append ({'Team':team,'total_score':total_score, 'Group': str(df1.Group.unique())})
    team_score=pd.DataFrame(team_score)
    return team_score

In [455]:
#Calculate rank for each group
sc=score_calc(fixture)
sc.set_index(['Group','Team'],inplace=True)
sc.sort_index(inplace=True)

df=sc.groupby(level="Group",sort=True,as_index=True)['total_score'].rank(ascending=False,method='dense')
score_df=df.reset_index()  

score_df.head()

         Group          Team  total_score
0  ['Group A']         Egypt          2.0
1  ['Group A']        Russia          3.0
2  ['Group A']  Saudi-Arabia          4.0
3  ['Group A']       Uruguay          1.0
4  ['Group B']          Iran          3.0

In [456]:
###Assign Teams for Round of 16 matches
wc_2018=world_cup_result[(world_cup_result.Year==2018)]
Round_of_16 = wc_2018[ wc_2018.Round=="Round of 16"]

Round_of_16.Team_A[0:1]=score_df[ (score_df.Group=="['Group A']") & (score_df.total_score==1.0)]["Team"]
Round_of_16.Team_B[0:1]=score_df[ (score_df.Group=="['Group B']") & (score_df.total_score==2.0)]["Team"]

Round_of_16.Team_A[1:2]=score_df[ (score_df.Group=="['Group C']") & (score_df.total_score==1.0)]["Team"]
Round_of_16.Team_B[1:2]=score_df[ (score_df.Group=="['Group D']") & (score_df.total_score==2.0)]["Team"]

Round_of_16.Team_A[2:3]=score_df[ (score_df.Group=="['Group B']") & (score_df.total_score==1.0)]["Team"]
Round_of_16.Team_B[2:3]=score_df[ (score_df.Group=="['Group A']") & (score_df.total_score==2.0)]["Team"]

Round_of_16.Team_A[3:4]=score_df[ (score_df.Group=="['Group D']") & (score_df.total_score==1.0)]["Team"]
Round_of_16.Team_B[3:4]=score_df[ (score_df.Group=="['Group C']") & (score_df.total_score==2.0)]["Team"]

Round_of_16.Team_A[4:5]=score_df[ (score_df.Group=="['Group E']") & (score_df.total_score==1.0)]["Team"]
Round_of_16.Team_B[4:5]=score_df[ (score_df.Group=="['Group F']") & (score_df.total_score==2.0)]["Team"]

Round_of_16.Team_A[5:6]=score_df[ (score_df.Group=="['Group G']") & (score_df.total_score==1.0)]["Team"]
Round_of_16.Team_B[5:6]=score_df[ (score_df.Group=="['Group H']") & (score_df.total_score==2.0)]["Team"]

Round_of_16.Team_A[6:7]=score_df[ (score_df.Group=="['Group F']") & (score_df.total_score==1.0)]["Team"]
Round_of_16.Team_B[6:7]=score_df[ (score_df.Group=="['Group E']") & (score_df.total_score==2.0)]["Team"]

Round_of_16.Team_A[7:8]=score_df[ (score_df.Group=="['Group H']") & (score_df.total_score==1.0)]["Team"]
Round_of_16.Team_B[7:8]=score_df[ (score_df.Group=="['Group G']") & (score_df.total_score==2.0)]["Team"]

C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\series.py:934: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._set_with(key, value)
C:\Users\Kuntal\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2963: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [457]:
###Update historical data based on group round result
historical_data_earlier = world_cup_result[world_cup_result.Year<2018]
historical_data_2018 = world_cup_result[(world_cup_result.Year==2018) & (world_cup_result.Round=="Group")]

##Function to create Winner attributes. This variable will be used as dependent variable.
def winner_team(x):
    if x.Winner=="Team_A":
        val = x.Team_A
    elif x.Winner=="Team_B":
        val = x.Team_B
    else:
        val = "Draw"
    return (val)        

historical_data_2018.drop(columns='Winner',axis=1,inplace=True)

htd=pd.merge(historical_data_2018,fixture[['Month','Year','Team_A','Team_B','Winner']],on=['Month','Year','Team_A','Team_B'],how="left")
##Apply winner function
htd['Winner_Team']=htd.apply(winner_team,axis=1)

historical_data=pd.concat([historical_data_earlier,htd])
historical_data.Date = pd.to_datetime(historical_data.Date)

historical_data=pd.concat([historical_data,Round_of_16])

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\frame.py:3694: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

In [458]:
##Round of 16 feature engineering
World_cup_final_data_2 = feature_engineering_module(Round_of_16)

2018-06-30 00:00:00
2018-07-01 00:00:00
2018-07-02 00:00:00
2018-07-03 00:00:00
2018-06-30 00:00:00
2018-07-01 00:00:00
2018-07-02 00:00:00
2018-07-03 00:00:00

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\generic.py:4401: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

2018-06-30 00:00:00
2018-07-01 00:00:00
2018-07-02 00:00:00
2018-07-03 00:00:00
2018-06-30 00:00:00
2018-07-01 00:00:00
2018-07-02 00:00:00
2018-07-03 00:00:00
Date              datetime64[ns]
Team                      object
Total_match                int64
all_match_Draw             int64
all_match_win              int64
dtype: object
2018-06-30 00:00:00
2018-07-01 00:00:00
2018-07-02 00:00:00
2018-07-03 00:00:00
2018-06-30 00:00:00
2018-07-01 00:00:00
2018-07-02 00:00:00
2018-07-03 00:00:00

In [459]:
##Prediction for Round of 16
fixture=prediction_function(World_cup_final_data_2,"Round of 16")

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\frame.py:3787: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

In [461]:
fixture

,Round Number,Date,Location,Team_A,Team_B,Group,Result,Month,Year,Winner,Draw_prob,Team_A_prob,Team_B_prob
0,NaN,2018-06-30,NaN,Uruguay,Spain,NaN,Uruguay,NaN,NaN,Team_A,0.340,0.376,0.284
1,NaN,2018-06-30,NaN,France,Nigeria,NaN,France,NaN,NaN,Team_A,0.186,0.676,0.138
2,NaN,2018-07-01,NaN,Portugal,Egypt,NaN,Portugal,NaN,NaN,Team_A,0.178,0.627,0.195
3,NaN,2018-07-01,NaN,Argentina,Denmark,NaN,Argentina,NaN,NaN,Team_A,0.186,0.676,0.138
4,NaN,2018-07-02,NaN,Brazil,South-Korea,NaN,Brazil,NaN,NaN,Team_A,0.189,0.626,0.185
5,NaN,2018-07-02,NaN,Belgium,Senegal,NaN,Belgium,NaN,NaN,Team_A,0.186,0.676,0.138
6,NaN,2018-07-03,NaN,Germany,Switzerland,NaN,Germany,NaN,NaN,Team_A,0.233,0.455,0.312
7,NaN,2018-07-03,NaN,Poland,England,NaN,Poland,NaN,NaN,Team_A,0.235,0.537,0.228

In [462]:
###Assign Teams for Quarter-final matches
wc_2018=world_cup_result[(world_cup_result.Year==2018)]
QF = wc_2018[ wc_2018.Round=="Quarter-Finals"]
QF.Date = pd.to_datetime(QF.Date)

QF.Team_A[0:1]=fixture.Result[0]
QF.Team_B[0:1]=fixture.Result[1]

QF.Team_A[1:2]=fixture.Result[4]
QF.Team_B[1:2]=fixture.Result[5]

QF.Team_A[2:3]=fixture.Result[2]
QF.Team_B[2:3]=fixture.Result[3]

QF.Team_A[3:4]=fixture.Result[6]
QF.Team_B[3:4]=fixture.Result[7]

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\generic.py:4401: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\series.py:934: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._set_with(key, value)
C:\Users\Kuntal\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2963: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [463]:
historical_data=pd.concat([historical_data,QF])
historical_data.Date = pd.to_datetime(historical_data.Date)

C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.

In [464]:
##QF feature engineering
World_cup_QF = feature_engineering_module(QF)

2018-07-06T00:00:00.000000000
2018-07-07T00:00:00.000000000
2018-07-06T00:00:00.000000000
2018-07-07T00:00:00.000000000
2018-07-06 00:00:00
2018-07-07 00:00:00
2018-07-06 00:00:00

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\generic.py:4401: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

2018-07-07 00:00:00
Date              datetime64[ns]
Team                      object
Total_match                int64
all_match_Draw             int64
all_match_win              int64
dtype: object
2018-07-06 00:00:00
2018-07-07 00:00:00
2018-07-06 00:00:00
2018-07-07 00:00:00

In [465]:
##Prediction for QF
fixture=prediction_function(World_cup_QF,"Quarter-Finals")

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\frame.py:3787: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

In [466]:
fixture

,Round Number,Date,Location,Team_A,Team_B,Group,Result,Month,Year,Winner,Draw_prob,Team_A_prob,Team_B_prob
0,NaN,2018-07-06,NaN,Uruguay,France,NaN,Uruguay,NaN,NaN,Team_A,0.319,0.407,0.274
1,NaN,2018-07-06,NaN,Brazil,Belgium,NaN,Brazil,NaN,NaN,Team_A,0.317,0.473,0.210
2,NaN,2018-07-07,NaN,Portugal,Argentina,NaN,Portugal,NaN,NaN,Team_A,0.234,0.532,0.234
3,NaN,2018-07-07,NaN,Germany,Poland,NaN,Germany,NaN,NaN,Team_A,0.220,0.477,0.303

In [467]:
###Assign Teams for Quarter-final matches
wc_2018=world_cup_result[(world_cup_result.Year==2018)]
SF = wc_2018[ wc_2018.Round=="Semi-Finals"]
SF.Date = pd.to_datetime(SF.Date)

SF.Team_A[0:1]=fixture.Result[0]
SF.Team_B[0:1]=fixture.Result[1]

SF.Team_A[1:2]=fixture.Result[2]
SF.Team_B[1:2]=fixture.Result[3]

historical_data=pd.concat([historical_data,SF])
historical_data.Date = pd.to_datetime(historical_data.Date)

SF

##QF feature engineering
World_cup_SF = feature_engineering_module(SF)

##Prediction for SF
fixture=prediction_function(World_cup_SF,"Semi-Finals")

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\generic.py:4401: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\series.py:934: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._set_with(key, value)
C:\Users\Kuntal\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2963: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  if sys.path[0] == '':

2018-07-10T00:00:00.000000000
2018-07-11T00:00:00.000000000
2018-07-10T00:00:00.000000000
2018-07-11T00:00:00.000000000
2018-07-10 00:00:00
2018-07-11 00:00:00
2018-07-10 00:00:00
2018-07-11 00:00:00
Date              datetime64[ns]
Team                      object
Total_match                int64
all_match_Draw             int64
all_match_win              int64
dtype: object
2018-07-10 00:00:00
2018-07-11 00:00:00
2018-07-10 00:00:00
2018-07-11 00:00:00

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\frame.py:3787: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

In [468]:
fixture

,Round Number,Date,Location,Team_A,Team_B,Group,Result,Month,Year,Winner,Draw_prob,Team_A_prob,Team_B_prob
0,NaN,2018-07-10,NaN,Uruguay,Brazil,NaN,Uruguay,NaN,NaN,Team_A,0.295,0.413,0.292
1,NaN,2018-07-11,NaN,Portugal,Germany,NaN,Portugal,NaN,NaN,Team_A,0.233,0.545,0.222

In [469]:
###Assign Teams for Quarter-final matches
wc_2018=world_cup_result[(world_cup_result.Year==2018)]
Finals = wc_2018[ wc_2018.Round=="Finals"]
Finals.Date = pd.to_datetime(Finals.Date)

Finals.Team_A[0:1]=fixture.Result[0]
Finals.Team_B[0:1]=fixture.Result[1]

historical_data=pd.concat([historical_data,Finals])
historical_data.Date = pd.to_datetime(historical_data.Date)

Finals

##QF feature engineering
World_cup_Finals = feature_engineering_module(Finals)

##Prediction for Final
fixture=prediction_function(World_cup_Finals,"Final")

C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Kuntal\Anaconda3\lib\site-packages\pandas\core\series.py:934: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._set_with(key, value)
C:\Users\Kuntal\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2963: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\Kuntal\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  if __name__ == '__main__':

AttributeError: 'DataFrame' object has no attribute 'No_of_match_head_2_head_wc'

In [448]:
fixture

,Round Number,Date,Location,Team_A,Team_B,Group,Result,Month,Year,Winner,Draw_prob,Team_A_prob,Team_B_prob
0,NaN,2018-07-10,NaN,Uruguay,Brazil,NaN,Uruguay,NaN,NaN,Team_A,0.295,0.413,0.292
1,NaN,2018-07-11,NaN,Portugal,Germany,NaN,Portugal,NaN,NaN,Team_A,0.233,0.545,0.222